import { SEOPageData } from '@/components/SEOPage';

export const platformPages: Record<string, SEOPageData> = {
  'instagram-api': {
    slug: 'instagram-api',
    title: 'Instagram API',
    headline: 'Instagram API via StackPost',
    description: 'Publique posts, Reels e Stories no Instagram via API. Carrossel até 10 itens, primeiro comentário automático, Meta Graph API oficial.',
    category: 'platform',
    features: [
      { name: 'Post, Reel e Story', desc: 'Suporte completo aos três formatos do Instagram em um único endpoint.' },
      { name: 'Carrossel até 10 itens', desc: 'Múltiplas imagens e vídeos em um único post com ordem customizável.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 2.200 caracteres).' },
      { name: 'OAuth via Meta', desc: 'Fluxo OAuth oficial da Meta com set-channel obrigatório por conta.' },
      { name: 'Meta Graph API', desc: 'Integração direta com a Graph API da Meta, sem intermediários.' },
      { name: 'Áudio, localizações e tags', desc: 'Reels com música, locations e business discovery integrados.' },
    ],
    endpoints: [
      { method: 'POST', path: '/post', desc: 'Publicar no Instagram' },
      { method: 'POST', path: '/comment', desc: 'Comentar em posts' },
      { method: 'GET', path: '/analytics/post/raw', desc: 'Analytics brutos' },
    ],
  },
  'tiktok-api': {
    slug: 'tiktok-api',
    title: 'TikTok API',
    headline: 'TikTok API via StackPost',
    description: 'Publique vídeos e Photo Mode no TikTok via API. Content API oficial, status REVIEW, musicSoundInfo e primeiro comentário.',
    category: 'platform',
    features: [
      { name: 'Vídeo e Photo Mode', desc: 'Suporte aos dois formatos nativos do TikTok.' },
      { name: 'Photo Mode', desc: 'Aceita JPG e WebP. PNG é rejeitado pela API.' },
      { name: 'Status REVIEW', desc: 'Re-check automático do status de revisão até a aprovação.' },
      { name: 'musicSoundInfo', desc: 'Lista trending de músicas via CML para Reels.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 150 caracteres).' },
      { name: 'Content API oficial', desc: 'Integração direta com a TikTok Content API.' },
    ],
  },
  'facebook-api': {
    slug: 'facebook-api',
    title: 'Facebook API',
    headline: 'Facebook API via StackPost',
    description: 'Publique posts em Page, Reels e Stories no Facebook via API. Meta Graph API, primeiro comentário até 8.000 caracteres.',
    category: 'platform',
    features: [
      { name: 'Page post, Reel e Story', desc: 'Suporte completo aos formatos do Facebook.' },
      { name: '4 imagens ou 1 vídeo', desc: 'Mídia por post com validação automática.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 8.000 caracteres).' },
      { name: 'OAuth Meta', desc: 'Selecione TODAS as Pages durante o fluxo OAuth.' },
      { name: 'Meta Graph API', desc: 'Integração oficial com a Meta Graph API.' },
      { name: 'Auto Reply', desc: 'Resposta automática a comentários recebidos.' },
    ],
  },
  'youtube-api': {
    slug: 'youtube-api',
    title: 'YouTube API',
    headline: 'YouTube API via StackPost',
    description: 'Publique vídeos e Shorts no YouTube via API. Data API v3, campo madeForKids obrigatório, analytics com monetização.',
    category: 'platform',
    features: [
      { name: 'Vídeo e Shorts', desc: 'Shorts auto-detectados por duração (até 60s).' },
      { name: 'madeForKids obrigatório', desc: 'Campo obrigatório por conformidade COPPA.' },
      { name: 'Título 100 caracteres', desc: 'Descrição até 5.000 caracteres por vídeo.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 10.000 caracteres).' },
      { name: 'Analytics com monetização', desc: 'withBusinessScope + rawYoutubeAnalyticsEnabled.' },
      { name: 'Playlists', desc: 'CRUD completo de playlists e itens.' },
    ],
  },
  'linkedin-api': {
    slug: 'linkedin-api',
    title: 'LinkedIn API',
    headline: 'LinkedIn API via StackPost',
    description: 'Publique no perfil e Company Pages do LinkedIn via API. Texto, mídia, link e documento. Mentions e primeiro comentário.',
    category: 'platform',
    features: [
      { name: 'Perfil e Company Page', desc: 'set-channel: perfil pessoal ou página de empresa.' },
      { name: 'Texto, mídia, link e doc', desc: 'Até 10 mídias ou 1 PDF por post.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 1.250 caracteres).' },
      { name: 'Mentions builder', desc: 'Construa menções via /misc/linkedin/mentions/builder.' },
      { name: 'Marketing API', desc: 'Integração oficial com a LinkedIn Marketing API.' },
      { name: 'mediaTitle 200 caracteres', desc: 'Título de mídia suportado em cada post.' },
    ],
  },
  'x-api': {
    slug: 'x-api',
    title: 'X API',
    headline: 'X (Twitter) API via StackPost',
    description: 'Publique tweets com mídia via API v2. Até 4 imagens ou 1 vídeo. Cobrança pré-paga por post.',
    category: 'platform',
    features: [
      { name: 'Tweet com mídia', desc: 'Até 4 imagens ou 1 vídeo por tweet.' },
      { name: 'Texto 280 / 25.000 caracteres', desc: 'Limite de texto flexível conforme o tipo de conta.' },
      { name: 'API v2', desc: 'Integração oficial com a X API v2.' },
      { name: 'OAuth direto', desc: 'Sem necessidade de set-channel.' },
      { name: 'Créditos pré-pagos', desc: 'US$ 0,015/post; US$ 0,20/post com link.' },
      { name: 'Sem primeiro comentário', desc: 'O X não suporta comentários via API.' },
    ],
  },
  'threads-api': {
    slug: 'threads-api',
    title: 'Threads API',
    headline: 'Threads API via StackPost',
    description: 'Publique no Threads via API. Texto, mídia, enquete, GIF e link. Até 10 imagens ou 1 vídeo. Primeiro comentário.',
    category: 'platform',
    features: [
      { name: 'Texto, mídia, poll, GIF e link', desc: 'Todos os formatos nativos do Threads.' },
      { name: '10 imagens ou 1 vídeo', desc: 'Multi-mídia por post com validação automática.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 500 caracteres).' },
      { name: 'OAuth direto', desc: 'Sem necessidade de set-channel.' },
      { name: 'Meta API', desc: 'Integração via Meta com autenticação oficial.' },
    ],
  },
  'pinterest-api': {
    slug: 'pinterest-api',
    title: 'Pinterest API',
    headline: 'Pinterest API via StackPost',
    description: 'Publique pins no Pinterest via API v5. Board obrigatório, 1 imagem ou vídeo por pin.',
    category: 'platform',
    features: [
      { name: 'Pin com board', desc: 'BoardName obrigatório para cada publicação.' },
      { name: '1 imagem ou vídeo', desc: 'Mídia única por pin com validação automática.' },
      { name: 'API v5', desc: 'Integração oficial com a Pinterest API v5.' },
      { name: 'OAuth sem set-channel', desc: 'Boards sincronizados via refresh automático.' },
      { name: 'Sem primeiro comentário', desc: 'O Pinterest não suporta comentários via API.' },
    ],
  },
  'reddit-api': {
    slug: 'reddit-api',
    title: 'Reddit API',
    headline: 'Reddit API via StackPost',
    description: 'Publique texto, link, mídia e gallery no Reddit via API. Subreddit obrigatório, verificação de post-requirements.',
    category: 'platform',
    features: [
      { name: 'Texto, link, mídia e gallery', desc: 'Todos os formatos nativos do Reddit.' },
      { name: 'Subreddit obrigatório', desc: 'Campo sr obrigatório em toda publicação.' },
      { name: 'Post-requirements', desc: 'Validação via /misc/reddit/post-requirements ANTES de postar.' },
      { name: 'Subreddit flairs', desc: 'Listagem de flairs via /misc/reddit/subreddit-flairs.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 10.000 caracteres).' },
      { name: 'Texto 300, descrição 30.000', desc: 'Limites de texto por tipo de post.' },
    ],
  },
  'bluesky-api': {
    slug: 'bluesky-api',
    title: 'Bluesky API',
    headline: 'Bluesky API via StackPost',
    description: 'Publique no Bluesky via AT Protocol. Texto, mídia, link card e quote. Até 4 mídias, primeiro comentário.',
    category: 'platform',
    features: [
      { name: 'AT Protocol', desc: 'Protocolo aberto e descentralizado, sem lock-in.' },
      { name: 'Texto, mídia, link card e quote', desc: 'Todos os formatos suportados pelo Bluesky.' },
      { name: '4 mídias', desc: 'Multi-mídia por post com validação automática.' },
      { name: 'serverUrl opcional', desc: 'Padrão bsky.social. Instância custom suportada.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 300 caracteres).' },
      { name: 'Texto 300 caracteres', desc: 'Limite de texto por post.' },
    ],
  },
  'mastodon-api': {
    slug: 'mastodon-api',
    title: 'Mastodon API',
    headline: 'Mastodon API via StackPost',
    description: 'Publique no Mastodon via API. Instância custom, até 4 mídias, privacidade e spoiler text. Primeiro comentário.',
    category: 'platform',
    features: [
      { name: 'Instância custom', desc: 'serverUrl obrigatório. Suporte a qualquer instância Mastodon.' },
      { name: '4 mídias', desc: 'Multi-mídia por status com validação automática.' },
      { name: 'Privacidade + spoiler', desc: 'Controle de privacidade e spoiler text por post.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 500 caracteres).' },
      { name: 'Status', desc: 'Publicação de status com mídia anexada.' },
    ],
  },
  'slack-api': {
    slug: 'slack-api',
    title: 'Slack API',
    headline: 'Slack API via StackPost',
    description: 'Publique mensagens no Slack via webhook URL. Até 4 attachments, texto até 30.000 caracteres, primeiro comentário.',
    category: 'platform',
    features: [
      { name: 'Webhook URL', desc: 'Integração via webhook nativo do Slack.' },
      { name: 'channelId obrigatório', desc: 'Canal específico para cada publicação.' },
      { name: '4 attachments', desc: 'Anexos por mensagem com validação automática.' },
      { name: 'Texto 30.000 caracteres', desc: 'Limite de texto generoso por mensagem.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 30.000 caracteres).' },
    ],
  },
  'discord-api': {
    slug: 'discord-api',
    title: 'Discord API',
    headline: 'Discord API via StackPost',
    description: 'Publique mensagens no Discord via webhook URL. Até 10 attachments, texto até 2.000 caracteres, primeiro comentário.',
    category: 'platform',
    features: [
      { name: 'Webhook URL', desc: 'Integração via webhook nativo do Discord.' },
      { name: 'channelId obrigatório', desc: 'Canal específico para cada publicação.' },
      { name: '10 attachments', desc: 'Anexos por mensagem com validação automática.' },
      { name: 'Texto 2.000 caracteres', desc: 'Limite de texto por mensagem.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após publicar (até 2.000 caracteres).' },
    ],
  },
  'google-business-api': {
    slug: 'google-business-api',
    title: 'Google Business Profile API',
    headline: 'Google Business API via StackPost',
    description: 'Publique posts no Google Business Profile via API. STANDARD, EVENT, OFFER e ALERT. Location management completo.',
    category: 'platform',
    features: [
      { name: 'STANDARD, EVENT, OFFER e ALERT', desc: 'Quatro tipos de post suportados.' },
      { name: 'Location management', desc: 'CRUD de location, attributes, categories, food-menus e hours.' },
      { name: 'set-channel: location', desc: 'Local específico para cada publicação.' },
      { name: '1 imagem, texto 1.500', desc: 'Mídia e texto por post com validação automática.' },
      { name: 'Reviews API', desc: 'Importação e resposta de reviews de clientes.' },
      { name: 'Sem primeiro comentário', desc: 'O Google Business Profile não suporta.' },
    ],
  },
  'snapchat-api': {
    slug: 'snapchat-api',
    title: 'Snapchat API',
    headline: 'Snapchat API via StackPost',
    description: 'Publique Stories e Spotlights no Snapchat via Marketing API. Public Profile, 1 mídia por post.',
    category: 'platform',
    features: [
      { name: 'Story e Spotlight', desc: 'Dois formatos nativos suportados.' },
      { name: 'Public Profile', desc: 'OAuth via Public Profile do Snapchat.' },
      { name: '1 mídia por post', desc: 'Mídia única com validação automática.' },
      { name: 'Marketing API', desc: 'Integração oficial com a Snapchat Marketing API.' },
      { name: 'Sem primeiro comentário', desc: 'O Snapchat não suporta via API.' },
    ],
  },
};

export const apiPages: Record<string, SEOPageData> = {
  'social-media-api': {
    slug: 'social-media-api',
    title: 'Social Media API',
    headline: 'API unificada para redes sociais',
    description: 'Uma única API para 15 plataformas de redes sociais. Publicação paralela, agendamento, analytics, comentários e mais.',
    category: 'api',
    features: [
      { name: '15 plataformas', desc: 'Instagram, TikTok, YouTube, Facebook, LinkedIn, X, Threads, Pinterest, Reddit, Bluesky, Mastodon, Discord, Slack, Google Business e Snapchat.' },
      { name: 'Publicação paralela', desc: 'Promise.allSettled. Falha em uma plataforma não afeta as demais.' },
      { name: '114 endpoints', desc: 'API REST completa com especificação OpenAPI 3.1.' },
      { name: 'Autenticação por API Key', desc: 'Header x-api-key no padrão Stripe-like.' },
      { name: 'Rate limit em 3 camadas', desc: '100/1s, 500/10s e 2.000/60s por equipe.' },
      { name: 'Webhooks', desc: '9 eventos com assinatura HMAC-SHA256 e replay suportado.' },
    ],
  },
  'posting-api': {
    slug: 'posting-api',
    title: 'Posting API',
    headline: 'API de publicação para redes sociais',
    description: 'Publique em 15 plataformas com uma única requisição. Validação por plataforma, primeiro comentário, rascunho e agendamento.',
    category: 'api',
    features: [
      { name: 'POST /post', desc: 'Endpoint unificado que valida regras específicas por plataforma.' },
      { name: 'DRAFT ou SCHEDULED', desc: 'Salve como rascunho ou agende para publicação futura.' },
      { name: 'Primeiro comentário', desc: 'Comente automaticamente após a publicação.' },
      { name: 'Idempotency-Key', desc: 'Previne duplicação em retries e reenvios.' },
      { name: 'errorsVerbose', desc: 'Erros padronizados com code, userFacingMessage e isTransient.' },
      { name: 'Retry transient', desc: '3 retries automáticos com backoff 30s/90s/270s.' },
    ],
  },
  'scheduling-api': {
    slug: 'scheduling-api',
    title: 'Scheduling API',
    headline: 'API de agendamento para redes sociais',
    description: 'Agende posts para qualquer horário. Cron job processa no momento certo. Best-time-to-post com ML.',
    category: 'api',
    features: [
      { name: 'Agendamento', desc: 'postDate no futuro processado por cron job automático.' },
      { name: 'Best-time-to-post', desc: 'ML sugere os 3 melhores horários por conta.' },
      { name: 'Calendar view', desc: 'Calendário visual de posts agendados.' },
      { name: 'Drag-and-drop', desc: 'Reagende arrastando posts no calendário.' },
      { name: 'Approval workflow', desc: 'Fluxo DRAFT → REVIEW → APPROVED → SCHEDULED.' },
    ],
  },
  'media-upload-api': {
    slug: 'media-upload-api',
    title: 'Media Upload API',
    headline: 'API de upload de mídia',
    description: '4 métodos de upload: simple, direct, multipart e from-url. Protocolo tus. Cloudflare R2 com zero egress.',
    category: 'api',
    features: [
      { name: 'Simple upload', desc: 'Multipart/form-data, até 90 MB por arquivo.' },
      { name: 'Direct upload', desc: 'Presigned URL do R2 com validade de 30 minutos.' },
      { name: 'Multipart resumable', desc: 'Chunks de 64 MiB, validade 6h, até 10.000 partes.' },
      { name: 'Upload from URL', desc: 'Importe mídia de qualquer URL, até 1 GB.' },
      { name: 'Protocolo tus', desc: 'Padrão da indústria com bibliotecas em todas as linguagens.' },
      { name: 'Cloudflare R2', desc: 'Compatível com S3. ZERO taxa de egress.' },
    ],
  },
  'bulk-posting': {
    slug: 'bulk-posting',
    title: 'Bulk Posting API',
    headline: 'API de publicação em lote',
    description: 'Publique em lote via CSV ou API. Centenas de posts por requisição. Resultados detalhados por linha.',
    category: 'api',
    features: [
      { name: 'Importação via CSV', desc: 'POST /post-csv-import com resultados por linha.' },
      { name: 'API bulk', desc: 'POST /post/bulk para centenas de posts por requisição.' },
      { name: 'Limite 100 posts', desc: 'Por requisição. Acima disso, fracionar em múltiplas chamadas.' },
      { name: 'Resultados detalhados', desc: 'Sucesso ou erro individual por linha processada.' },
    ],
  },
  'post-history-api': {
    slug: 'post-history-api',
    title: 'Post History API',
    headline: 'API de histórico de posts',
    description: 'Importe o histórico de posts de 15 plataformas. Limites por plano. Retenção de 30 dias.',
    category: 'api',
    features: [
      { name: '15 plataformas', desc: 'Importe de todas as plataformas suportadas.' },
      { name: 'Importação assíncrona', desc: 'POST /post-history-import processado por worker.' },
      { name: 'Limites por plano', desc: 'FREE 5 / STARTER 50 / GROWTH 200 / SCALE 500 / BUSINESS 1.000 por conta/mês.' },
      { name: 'Limite 100 por requisição', desc: 'Posts por chamada. Acima disso, fracionar.' },
    ],
  },
  'comments-api': {
    slug: 'comments-api',
    title: 'Comments API',
    headline: 'API de comentários',
    description: 'Publique e importe comentários em 11 plataformas via API unificada. Reply automation e comment-to-DM.',
    category: 'api',
    features: [
      { name: 'POST /comment', desc: 'Comente em 11 plataformas com um único endpoint.' },
      { name: 'POST /comment/import', desc: 'Importe comentários de 9 plataformas.' },
      { name: 'Reply automation', desc: 'Responda comentários automaticamente com regras.' },
      { name: 'Comment to DM', desc: 'Converta comentários em DM no Instagram e Facebook.' },
      { name: 'Limites por plano', desc: 'FREE 25 / STARTER 100 / GROWTH 400 / SCALE 1.000 / BUSINESS 2.000 por post.' },
    ],
  },
  'analytics-api': {
    slug: 'analytics-api',
    title: 'Analytics API',
    headline: 'API de analytics',
    description: 'Métricas normalizadas e raw analytics por plataforma. Histórico indefinido. Monetização no YouTube.',
    category: 'api',
    features: [
      { name: 'Métricas normalizadas', desc: 'Impressions, views, likes, comments, shares e saves.' },
      { name: 'Raw analytics', desc: 'Dados brutos por plataforma, sem processamento.' },
      { name: 'Histórico indefinido', desc: 'Cron job diário salva snapshot. Gráfico de evolução.' },
      { name: 'Monetização no YouTube', desc: 'withBusinessScope + rawYoutubeAnalyticsEnabled.' },
      { name: 'Force refresh', desc: 'POST /analytics/post/force com rate limit por equipe.' },
      { name: 'Retenção 30 dias', desc: 'Configurável para indefinido no StackPost.' },
    ],
  },
  'first-comment-api': {
    slug: 'first-comment-api',
    title: 'First Comment API',
    headline: 'API de primeiro comentário',
    description: 'Comente automaticamente após publicar. Suporte por plataforma com limites específicos.',
    category: 'api',
    features: [
      { name: 'Comentário automático', desc: 'Agendado após o sucesso da publicação.' },
      { name: 'Limites por plataforma', desc: 'Instagram 2.200, LinkedIn 1.250, TikTok 150, entre outros.' },
      { name: 'Suporte amplo', desc: '12 das 15 plataformas suportam primeiro comentário.' },
    ],
  },
  'unified-api': {
    slug: 'unified-api',
    title: 'Unified API',
    headline: 'API unificada de redes sociais',
    description: 'Uma integração, 15 plataformas. Input unificado e o sistema adapta para cada rede.',
    category: 'api',
    features: [
      { name: 'Input unificado', desc: 'text, media, hashtags e link em um único payload.' },
      { name: 'Cross-post adaptativo', desc: 'O sistema gera data.PLATFORM automaticamente por plataforma.' },
      { name: 'Edição antes de publicar', desc: 'O usuário edita cada versão antes do envio.' },
      { name: '15 plataformas', desc: 'Uma única integração para todas as redes suportadas.' },
    ],
  },
};

export const comparisonPages: Record<string, SEOPageData> = {
  'ayrshare-alternative': {
    slug: 'ayrshare-alternative',
    title: 'Ayrshare Alternative',
    headline: 'StackPost: a melhor alternativa ao Ayrshare',
    description: 'API de redes sociais developer-first com 15 plataformas, MCP server, legendas com IA, A/B testing e multi-usuário com RBAC — sem cobrança por seat e com preços em reais.',
    category: 'comparison',
    features: [
      { name: '15 plataformas', desc: 'Mesma cobertura do Ayrshare em um único endpoint REST.' },
      { name: 'MCP server', desc: 'Agents de IA publicam posts via Model Context Protocol. O Ayrshare não oferece.' },
      { name: 'Legendas com IA', desc: 'Integração nativa com Nexus IA gera variações de copy. O Ayrshare não tem.' },
      { name: 'Analytics ilimitado', desc: 'O Ayrshare retém 30 dias; o StackPost guarda o histórico indefinidamente.' },
      { name: 'Multi-usuário com RBAC', desc: 'O Ayrshare cobra por seat; o StackPost inclui em todos os planos.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago. O Ayrshare cobra em USD com IOF.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Ayrshare?', a: 'Sim. O StackPost é uma API developer-first para times que precisam de uma integração única entre todas as principais plataformas, com preços transparentes por uso e sem taxas por usuário.' },
      { q: 'Posso migrar do Ayrshare?', a: 'Sim. A API do StackPost segue padrões REST similares e nossa equipe acompanha a migração passo a passo.' },
    ],
  },
  'zernio-alternative': {
    slug: 'zernio-alternative',
    title: 'Alternativa ao Zernio',
    headline: 'StackPost: a alternativa completa ao Zernio',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. Contas sociais ilimitadas em todos os planos pagos e cobrança por uso de API — não por conta. O Zernio cobra por conta conectada; o StackPost inclui contas ilimitadas e ainda entrega automação programável.',
    category: 'comparison',
    features: [
      { name: 'Contas ilimitadas', desc: 'Todos os planos pagos incluem contas sociais ilimitadas. O Zernio cobra por conta conectada, encarecendo a operação conforme a equipe cresce.' },
      { name: 'API REST completa', desc: '114 endpoints documentados com OpenAPI 3.1. O Zernio não expõe API pública para automação.' },
      { name: 'MCP server + CLI', desc: 'Agents de IA publicam posts via Model Context Protocol direto no terminal. O Zernio não oferece.' },
      { name: 'A/B testing de conteúdo', desc: 'Teste variações de legenda e mensure o desempenho de cada versão. O Zernio não tem.' },
      { name: 'Best-time-to-post com ML', desc: 'Sugestão dos 3 melhores horários por conta com machine learning. O Zernio não tem.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem variação cambial. O Zernio cobra em USD.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Zernio?', a: 'Sim. O StackPost vai além do agendamento: entrega API REST, MCP server, A/B testing e contas ilimitadas em todos os planos pagos, ideal para developers e times que precisam de automação e integração programável sem custos por conta.' },
      { q: 'Posso migrar do Zernio?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração das suas contas, conteúdo e agendamentos passo a passo.' },
    ],
  },
  'postiz-alternative': {
    slug: 'postiz-alternative',
    title: 'Alternativa ao Postiz',
    headline: 'StackPost: a alternativa completa ao Postiz',
    description: 'Plataforma developer-first com API REST de 114 endpoints, dashboard e MCP server. O Postiz é uma ferramenta visual de agendamento — o StackPost é API + interface + automação programável em um só lugar.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: '114 endpoints documentados com OpenAPI 3.1. O Postiz não expõe API pública.' },
      { name: 'MCP server', desc: 'Agents de IA publicam posts via Model Context Protocol. O Postiz não oferece.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática. O Postiz não tem.' },
      { name: 'SDK + CLI', desc: 'Bibliotecas em TypeScript, Python e Go. O Postiz não fornece.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Postiz tem planos limitados.' },
      { name: 'Analytics com histórico', desc: 'Retenção indefinida de métricas. O Postiz não guarda histórico.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Postiz?', a: 'Sim. O StackPost vai além do agendamento visual: entrega API REST, MCP server, webhooks e multi-usuário com RBAC, ideal para developers e times que precisam de automação e integração programável.' },
      { q: 'Posso migrar do Postiz?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
  'metricool-alternative': {
    slug: 'metricool-alternative',
    title: 'Alternativa ao Metricool',
    headline: 'StackPost: a alternativa completa ao Metricool',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O Metricool é só dashboard — o StackPost é API + interface + automação em um só lugar.',
    category: 'comparison',
    features: [
      { name: 'API REST pública', desc: 'Integre e automatize via HTTP. O Metricool não oferece API pública.' },
      { name: 'MCP server + CLI', desc: 'Automação com agentes de IA direto no terminal. O Metricool não tem.' },
      { name: 'Webhooks com replay', desc: 'Eventos em tempo real e reprocessamento garantido. O Metricool não tem.' },
      { name: 'A/B testing de conteúdo', desc: 'Teste variações de posts e mensure o desempenho. O Metricool não tem.' },
      { name: 'Legendas com IA', desc: 'Geração de copy com Nexus IA integrada. O Metricool não tem.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão.' },
    ],
  },
  'publer-alternative': {
    slug: 'publer-alternative',
    title: 'Alternativa ao Publer',
    headline: 'StackPost: a alternativa completa ao Publer',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O Publer é apenas um dashboard de agendamento — o StackPost é API + interface + automação para developers e times.',
    category: 'comparison',
    features: [
      { name: 'API REST pública', desc: 'Integre e automatize via HTTP. O Publer não oferece API pública.' },
      { name: 'MCP server', desc: 'Agents de IA publicam via Model Context Protocol. O Publer não tem.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática. O Publer não tem.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Publer cobra por usuário.' },
      { name: 'Analytics com histórico', desc: 'Retenção indefinida de métricas. O Publer limita o histórico.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão cambial.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Publer?', a: 'Sim. O StackPost entrega API REST, MCP server, webhooks e multi-usuário com RBAC — recursos que o Publer não oferece — ideal para developers e times que precisam de automação programável.' },
      { q: 'Posso migrar do Publer?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
  'buffer-alternative': {
    slug: 'buffer-alternative',
    title: 'Alternativa ao Buffer',
    headline: 'StackPost: a alternativa ao Buffer para developers e times',
    description: 'API developer-first com 15 plataformas, MCP server e A/B testing. O Buffer é uma ferramenta simples de agendamento — o StackPost é uma plataforma completa de publicação e automação.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: 'Automação total via HTTP. O Buffer tem API limitada.' },
      { name: '15 plataformas', desc: 'Cobertura ampla de canais. O Buffer suporta menos.' },
      { name: 'MCP server', desc: 'Integração com agentes de IA. O Buffer não tem.' },
      { name: 'A/B testing', desc: 'Teste variações de conteúdo com dados. O Buffer não tem.' },
      { name: 'Legendas com IA', desc: 'Geração de copy com Nexus IA. O Buffer tem IA básica.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão.' },
    ],
  },
  'socialpilot-alternative': {
    slug: 'socialpilot-alternative',
    title: 'Alternativa ao SocialPilot',
    headline: 'StackPost: a alternativa completa ao SocialPilot',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O SocialPilot é apenas um dashboard de agendamento — o StackPost é API + interface + automação para developers e times.',
    category: 'comparison',
    features: [
      { name: 'API REST pública', desc: 'Integre e automatize via HTTP. O SocialPilot não oferece API pública.' },
      { name: 'MCP server + CLI', desc: 'Automação com agentes de IA direto no terminal. O SocialPilot não tem.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática. O SocialPilot não tem.' },
      { name: 'A/B testing de conteúdo', desc: 'Teste variações de posts e mensure o desempenho. O SocialPilot não tem.' },
      { name: 'Analytics com histórico', desc: 'Retenção indefinida de métricas. O SocialPilot limita o histórico.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão cambial.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao SocialPilot?', a: 'Sim. O StackPost entrega API REST, MCP server, webhooks e A/B testing — recursos que o SocialPilot não oferece — ideal para developers e times que precisam de automação programável.' },
      { q: 'Posso migrar do SocialPilot?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
  'blotato-alternative': {
    slug: 'blotato-alternative',
    title: 'Blotato Alternative',
    headline: 'StackPost: a melhor alternativa ao Blotato',
    description: 'API developer-first com 15 plataformas, MCP server, webhooks com replay e multi-usuário com RBAC. O Blotato é uma ferramenta simples de agendamento; o StackPost é uma plataforma completa para developers e times.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: '114 endpoints documentados. O Blotato não expõe API pública.' },
      { name: '15 plataformas', desc: 'Cobertura completa em um único endpoint. O Blotato tem menos.' },
      { name: 'MCP server', desc: 'Agents de IA publicam via Model Context Protocol. O Blotato não oferece.' },
      { name: 'Webhooks com replay', desc: '9 eventos com retentativa automática. O Blotato não tem.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Blotato não tem.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem variação cambial.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Blotato?', a: 'Sim. O StackPost vai além do agendamento: entrega API REST, MCP server, webhooks e multi-usuário com RBAC, ideal para developers e times que precisam de automação e integração programável.' },
      { q: 'Posso migrar do Blotato?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
};

export const specializedPages: Record<string, SEOPageData> = {
  'instagram-auto-reply': {
    slug: 'instagram-auto-reply',
    title: 'Instagram Auto Reply API',
    headline: 'Instagram Auto Reply API',
    description: 'Resposta automática a comentários no Instagram. Configure regras inteligentes e o bot responde por você em tempo real, aumentando o engajamento sem esforço manual.',
    category: 'specialized',
    features: [
      { name: 'Auto-resposta', desc: 'Responda comentários automaticamente com mensagens personalizadas e contextuais.' },
      { name: 'Regras customizáveis', desc: 'Filtre por palavra-chave, horário e tipo de publicação para respostas precisas.' },
      { name: 'Comment to DM', desc: 'Converta comentários públicos em conversas privadas via DM automaticamente.' },
    ],
  },
  'facebook-auto-reply': {
    slug: 'facebook-auto-reply',
    title: 'Facebook Auto Reply API',
    headline: 'Facebook Auto Reply API',
    description: 'Resposta automática a comentários no Facebook. Configure regras inteligentes e o bot responde por você em tempo real, escalando o atendimento sem esforço manual.',
    category: 'specialized',
    features: [
      { name: 'Auto-resposta', desc: 'Responda comentários automaticamente com mensagens personalizadas e contextuais.' },
      { name: 'Regras customizáveis', desc: 'Filtre por palavra-chave, horário e tipo de publicação para respostas precisas.' },
      { name: 'Comment to DM', desc: 'Converta comentários públicos em conversas privadas via Messenger automaticamente.' },
    ],
  },
  'meta-automation': {
    slug: 'meta-automation',
    title: 'Meta Automation API',
    headline: 'Meta Automation API',
    description: 'Automação completa para Instagram e Facebook em uma única API. Auto-reply, comment-to-DM e agendamento de posts unificados para escalar sua presença na Meta.',
    category: 'specialized',
    features: [
      { name: 'Instagram + Facebook', desc: 'Automação unificada para ambas as plataformas Meta em um único endpoint.' },
      { name: 'Auto-reply', desc: 'Resposta automática e contextual a comentários em todas as suas contas Meta.' },
      { name: 'Comment to DM', desc: 'Conversão automática de comentários em mensagens diretas para nutrir leads.' },
      { name: 'Post scheduling', desc: 'Agendamento inteligente de publicações com horário ótimo por plataforma.' },
    ],
  },
  'social-dm-api': {
    slug: 'social-dm-api',
    title: 'Social DM API',
    headline: 'Social DM API',
    description: 'Envie e gerencie mensagens diretas via API unificada. Instagram DM, Messenger e mais, tudo em um único endpoint para centralizar sua comunicação.',
    category: 'specialized',
    features: [
      { name: 'Instagram DM', desc: 'Direct messages no Instagram com suporte completo a envio e leitura.' },
      { name: 'Messenger', desc: 'Facebook Messenger integrado para atendimento conversacional em escala.' },
      { name: 'Comment to DM', desc: 'Converta comentários em DM automaticamente e migre conversas para o privado.' },
    ],
  },
  'comment-to-dm': {
    slug: 'comment-to-dm',
    title: 'Comment to DM API',
    headline: 'Comment to DM API',
    description: 'Converta comentários em mensagens diretas automaticamente no Instagram e Facebook. Transforme engajamento público em conversas privadas e qualificadas.',
    category: 'specialized',
    features: [
      { name: 'Instagram', desc: 'Comentário → DM no Instagram com gatilhos por palavra-chave ou menção.' },
      { name: 'Facebook', desc: 'Comentário → Messenger no Facebook para nutrir leads em conversas privadas.' },
      { name: 'Automação', desc: 'Fluxo totalmente automático, sem intervenção manual, 24/7.' },
    ],
  },
  'social-ads-api': {
    slug: 'social-ads-api',
    title: 'Social Ads API',
    headline: 'Social Ads API',
    description: 'Gerencie anúncios em redes sociais via API unificada. Meta Ads, Google Ads e mais, tudo em um único endpoint para centralizar e escalar suas campanhas.',
    category: 'specialized',
    features: [
      { name: 'Meta Ads', desc: 'Facebook e Instagram Ads com CRUD completo de campanhas e conjuntos de anúncios.' },
      { name: 'Google Ads', desc: 'Integração nativa com Google Ads para campanhas Search, Display e YouTube.' },
      { name: 'Multi-plataforma', desc: 'Uma única API para gerenciar anúncios em todas as plataformas suportadas.' },
    ],
  },
  'api-for-saas': {
    slug: 'api-for-saas',
    title: 'API for SaaS',
    headline: 'Social Media API for SaaS',
    description: 'Integre redes sociais no seu SaaS via API com white-label, multi-tenancy e webhooks. Uma infraestrutura pronta para escalar seu produto sem reinventar a roda.',
    category: 'specialized',
    features: [
      { name: 'White-label', desc: 'Sua marca, sua interface e sua identidade visual em toda a experiência.' },
      { name: 'Multi-tenancy', desc: 'Cada cliente seu tem sua própria organização isolada com dados segregados.' },
      { name: 'Webhooks', desc: '9 eventos em tempo real com assinatura HMAC-SHA256 para segurança total.' },
      { name: 'Rate limit', desc: '3 camadas de limite com headers X-RateLimit-* para controle granular.' },
    ],
  },
  'api-for-ai-agents': {
    slug: 'api-for-ai-agents',
    title: 'API for AI Agents',
    headline: 'Social Media API for AI Agents',
    description: 'MCP server para Claude, Cursor e AI agents. Crie, agende e analise posts via tools nativas, permitindo que seus agentes automatizem redes sociais sem código.',
    category: 'specialized',
    features: [
      { name: 'MCP server', desc: 'Model Context Protocol compatível com Claude, Cursor e qualquer LLM com suporte.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts, get_analytics e upload_media prontas.' },
      { name: 'stdio + HTTP', desc: 'Dois modos de operação flexíveis para qualquer arquitetura de agente.' },
      { name: 'AI caption', desc: 'Nexus IA gera de 3 a 5 variações de legendas otimizadas por plataforma.' },
    ],
  },
  'instagram-music-api': {
    slug: 'instagram-music-api',
    title: 'Instagram Music API',
    headline: 'Instagram Music API',
    description: 'Acesse a biblioteca de músicas do Instagram para Reels via API. Busque, liste e adicione músicas trending aos seus Reels para aumentar o alcance e a viralização.',
    category: 'specialized',
    features: [
      { name: 'Biblioteca de músicas', desc: 'Acesse o catálogo completo de músicas licenciadas do Instagram.' },
      { name: 'Trending', desc: 'Liste as músicas em alta para Reels e aproveite tendências em tempo real.' },
      { name: 'Busca por nome', desc: 'Encontre músicas por nome, artista ou gênero com filtros avançados.' },
      { name: 'Adição a Reels', desc: 'Adicione músicas aos seus Reels via API de forma programática.' },
      { name: 'Endpoint dedicado', desc: '/misc/instagram/audio para integração direta e simplificada.' },
    ],
  },
  'tiktok-music-api': {
    slug: 'tiktok-music-api',
    title: 'TikTok Music API',
    headline: 'TikTok Music API',
    description: 'Acesse a CML (Commercial Music Library) do TikTok via API. Liste músicas trending e adicione aos seus vídeos com licença comercial garantida.',
    category: 'specialized',
    features: [
      { name: 'CML trending list', desc: 'Commercial Music Library do TikTok com licença comercial para uso seguro.' },
      { name: 'Músicas em alta', desc: 'Liste as músicas trending do momento para surfar tendências virais.' },
      { name: 'Busca por nome', desc: 'Encontre músicas por nome ou artista com busca rápida e precisa.' },
      { name: 'Adição a vídeos', desc: 'Adicione músicas aos seus vídeos via API de forma programática.' },
      { name: 'Endpoint dedicado', desc: '/misc/tiktok/cml/trending-list para acesso direto ao catálogo.' },
    ],
  },
  'tiktok-content-posting-api': {
    slug: 'tiktok-content-posting-api',
    title: 'TikTok Content Posting API',
    headline: 'TikTok Content Posting API',
    description: 'Publique vídeos e Photo Mode no TikTok via Content API oficial. Status REVIEW, musicSoundInfo e first comment para um fluxo de publicação completo e profissional.',
    category: 'specialized',
    features: [
      { name: 'Content API oficial', desc: 'Integração direta com TikTok Content Posting API, sem gambiarras.' },
      { name: 'Vídeo e Photo Mode', desc: 'Suporte completo aos 2 formatos de publicação do TikTok.' },
      { name: 'Status REVIEW', desc: 'Re-check automático do status de revisão até a aprovação final.' },
      { name: 'musicSoundInfo', desc: 'Adicione músicas da CML com licença comercial ao seus vídeos.' },
      { name: 'First comment', desc: 'Comente automaticamente após publicar (máx 150 caracteres).' },
    ],
  },
  'instagram-comments-api': {
    slug: 'instagram-comments-api',
    title: 'Instagram Comments API',
    headline: 'Instagram Comments API',
    description: 'Leia, responda e gerencie comentários no Instagram via API. Suporte completo a comentários de feed e Reels para moderar e escalar o engajamento.',
    category: 'specialized',
    features: [
      { name: 'Ler comentários', desc: 'Liste comentários de posts e Reels com paginação e filtros.' },
      { name: 'Responder', desc: 'Responda comentários via API em escala, sem interface manual.' },
      { name: 'Gerenciar', desc: 'Delete e modere comentários indesejados para proteger sua reputação.' },
      { name: 'Auto-reply', desc: 'Resposta automática por regras inteligentes baseadas em palavra-chave.' },
      { name: 'Comment to DM', desc: 'Converta comentários em DM automaticamente para nutrir leads.' },
    ],
  },
  'facebook-comments-api': {
    slug: 'facebook-comments-api',
    title: 'Facebook Comments API',
    headline: 'Facebook Comments API',
    description: 'Leia, responda e gerencie comentários no Facebook Pages via API. Suporte completo a moderação para manter sua comunidade ativa e bem gerida.',
    category: 'specialized',
    features: [
      { name: 'Ler comentários', desc: 'Liste comentários de Page posts com paginação e filtros avançados.' },
      { name: 'Responder', desc: 'Responda comentários via API em escala, sem interface manual.' },
      { name: 'Gerenciar', desc: 'Delete e modere comentários indesejados para proteger sua marca.' },
      { name: 'Auto-reply', desc: 'Resposta automática por regras inteligentes baseadas em palavra-chave.' },
      { name: 'Comment to DM', desc: 'Converta comentários em Messenger automaticamente para nutrir leads.' },
    ],
  },
  'youtube-upload-api': {
    slug: 'youtube-upload-api',
    title: 'YouTube Upload API',
    headline: 'YouTube Upload API',
    description: 'Upload de vídeos para YouTube via Data API v3. Suporte a vídeos longos e Shorts, com madeForKids e thumbnails para um fluxo de publicação completo.',
    category: 'specialized',
    features: [
      { name: 'Data API v3', desc: 'Integração oficial com YouTube Data API v3, sem camadas intermediárias.' },
      { name: 'Vídeos longos e Shorts', desc: 'Suporte completo a ambos os formatos, com Shorts auto-detectados.' },
      { name: 'madeForKids', desc: 'Campo obrigatório por COPPA configurável via API para conformidade legal.' },
      { name: 'Thumbnails', desc: 'Upload e gerenciamento de thumbnails personalizados para cada vídeo.' },
      { name: 'Playlists', desc: 'CRUD completo de playlists e itens para organizar seu conteúdo.' },
    ],
  },
  'linkedin-company-page-api': {
    slug: 'linkedin-company-page-api',
    title: 'LinkedIn Company Page API',
    headline: 'LinkedIn Company Page API',
    description: 'Gerencie Company Pages do LinkedIn via API. Publique como empresa, mencione e analise performance para fortalecer sua presença corporativa no LinkedIn.',
    category: 'specialized',
    features: [
      { name: 'Publicar como empresa', desc: 'Post em nome da Company Page para fortalecer a voz da marca.' },
      { name: 'Mentions builder', desc: '/misc/linkedin/mentions/builder para citar empresas e perfis em posts.' },
      { name: 'Multi-mídia', desc: '10 mídias ou 1 PDF por post para enriquecer suas publicações.' },
      { name: 'First comment', desc: 'Comente automaticamente após publicar (máx 1.250 caracteres).' },
      { name: 'Marketing API', desc: 'Integração oficial com LinkedIn Marketing API para máxima confiabilidade.' },
    ],
  },
  'google-business-profile-reviews-api': {
    slug: 'google-business-profile-reviews-api',
    title: 'GBP Reviews API',
    headline: 'Google Business Profile Reviews API',
    description: 'Importe e responda reviews do Google Business Profile via API. Gerencie sua reputação online de forma centralizada e automatizada.',
    category: 'specialized',
    features: [
      { name: 'Importar reviews', desc: 'Importe reviews do Google Business Profile de forma programática.' },
      { name: 'Responder reviews', desc: 'Responda reviews via API para manter sua reputação ativa e responsiva.' },
      { name: 'Rating', desc: 'Acesse ratings e distribuição de estrelas para análise de satisfação.' },
      { name: 'Multi-location', desc: 'Reviews de múltiplas localidades centralizados em um único endpoint.' },
    ],
  },
  'google-business-profile-posts-api': {
    slug: 'google-business-profile-posts-api',
    title: 'GBP Posts API',
    headline: 'Google Business Profile Posts API',
    description: 'Publique posts no Google Business Profile via API. STANDARD, EVENT, OFFER e ALERT com location management completo para dominar o Google local.',
    category: 'specialized',
    features: [
      { name: '4 tipos de post', desc: 'STANDARD, EVENT, OFFER e ALERT para qualquer objetivo de comunicação.' },
      { name: 'Location management', desc: 'CRUD de locations, attributes e categories para gerenciar suas unidades.' },
      { name: 'Food menus', desc: 'Gerencie cardápios via API para restaurantes e estabelecimentos.' },
      { name: 'Hours', desc: 'Horários de funcionamento atualizados em tempo real via API.' },
      { name: 'Service list', desc: 'Lista de serviços publicada e atualizada automaticamente.' },
    ],
  },
  'meta-app-review-rejected': {
    slug: 'meta-app-review-rejected',
    title: 'Meta App Review',
    headline: 'Meta App Review Guide',
    description: 'Guia completo para passar na revisão de apps da Meta. Erros comuns de rejeição e como resolver cada um, com passo a passo para aprovação na primeira tentativa.',
    category: 'specialized',
    features: [
      { name: 'Erros comuns', desc: 'Lista de motivos de rejeição mais frequentes com soluções práticas.' },
      { name: 'Como resolver', desc: 'Passo a passo detalhado para cada tipo de rejeição identificada.' },
      { name: 'Permissões', desc: 'Quais permissões solicitar e como justificar cada uma para a Meta.' },
      { name: 'App Review', desc: 'Processo de revisão da Meta explicado do início à aprovação final.' },
      { name: 'Best practices', desc: 'Como estruturar o app para aprovação rápida e sem retrabalho.' },
    ],
  },
  'instagram-dm-api': {
    slug: 'instagram-dm-api',
    title: 'Instagram DM API',
    headline: 'Instagram DM API',
    description: 'Envie e gerencie mensagens diretas no Instagram via API. Integração com Instagram Messaging API para atendimento conversacional em escala.',
    category: 'specialized',
    features: [
      { name: 'Enviar DMs', desc: 'Mensagens diretas via API com suporte a texto, mídia e templates.' },
      { name: 'Ler DMs', desc: 'Liste e leia conversas completas para histórico e contexto de atendimento.' },
      { name: 'Comment to DM', desc: 'Converta comentários em DM automaticamente para migrar leads ao privado.' },
      { name: 'Auto-reply', desc: 'Resposta automática e contextual a DMs com regras inteligentes.' },
      { name: 'Webhooks', desc: 'Notificação em tempo real de novas DMs para resposta imediata.' },
    ],
  },
  'facebook-messenger-api': {
    slug: 'facebook-messenger-api',
    title: 'Messenger API',
    headline: 'Facebook Messenger API',
    description: 'Envie e gerencie mensagens no Facebook Messenger via API. Integração com Messenger Platform para atendimento conversacional em escala.',
    category: 'specialized',
    features: [
      { name: 'Enviar mensagens', desc: 'Mensagens via Messenger Platform com suporte a texto, mídia e templates.' },
      { name: 'Ler conversas', desc: 'Liste e leia conversas completas para histórico e contexto de atendimento.' },
      { name: 'Comment to DM', desc: 'Converta comentários em Messenger automaticamente para nutrir leads.' },
      { name: 'Auto-reply', desc: 'Resposta automática e contextual com regras inteligentes por palavra-chave.' },
      { name: 'Webhooks', desc: 'Notificação em tempo real de novas mensagens para resposta imediata.' },
    ],
  },
  'meta-ads-api': {
    slug: 'meta-ads-api',
    title: 'Meta Ads API',
    headline: 'Meta Ads API',
    description: 'Gerencie anúncios no Facebook e Instagram via Meta Marketing API. Campanhas, ad sets, ads e relatórios em um único endpoint para escalar suas campanhas.',
    category: 'specialized',
    features: [
      { name: 'Campanhas', desc: 'CRUD de campanhas via Meta Marketing API com objetivo e orçamento.' },
      { name: 'Ad sets', desc: 'Gerencie conjuntos de anúncios com segmentação e lances detalhados.' },
      { name: 'Ads', desc: 'Crie e edite anúncios com criativos, copy e call-to-action otimizados.' },
      { name: 'Relatórios', desc: 'Performance e métricas de anúncios em tempo real para decisões data-driven.' },
      { name: 'Audiences', desc: 'Custom e lookalike audiences para segmentação avançada e precisa.' },
    ],
  },
  'google-ads-api': {
    slug: 'google-ads-api',
    title: 'Google Ads API',
    headline: 'Google Ads API',
    description: 'Gerencie anúncios no Google via Google Ads API. Campanhas Search, Display, YouTube e Shopping em um único endpoint para dominar o ecossistema Google.',
    category: 'specialized',
    features: [
      { name: 'Campanhas', desc: 'CRUD de campanhas via Google Ads API com orçamento e segmentação.' },
      { name: 'Ad groups', desc: 'Gerencie grupos de anúncios com palavras-chave e lances otimizados.' },
      { name: 'Search/Display/YouTube', desc: 'Todos os tipos de campanha suportados em um único endpoint.' },
      { name: 'Relatórios', desc: 'Performance e métricas detalhadas para decisões data-driven em tempo real.' },
      { name: 'Conversões', desc: 'Tracking de conversões com atribuição para medir o ROI real.' },
    ],
  },
  'social-media-mcp-server': {
    slug: 'social-media-mcp-server',
    title: 'Social Media MCP Server',
    headline: 'Social Media MCP Server',
    description: 'Model Context Protocol server para AI agents. Claude, Cursor e qualquer LLM podem criar, agendar e analisar posts sem escrever uma linha de código.',
    category: 'specialized',
    features: [
      { name: 'MCP protocol', desc: 'Model Context Protocol da Anthropic para integração nativa com LLMs.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts, get_analytics e upload_media.' },
      { name: 'stdio + HTTP', desc: 'Dois modos de operação flexíveis para qualquer arquitetura de agente.' },
      { name: 'Claude integration', desc: 'Claude Code e Claude Desktop suportados nativamente, sem configuração extra.' },
      { name: 'Cursor integration', desc: 'Cursor IDE integrado para publicar posts direto do seu editor.' },
      { name: 'npm package', desc: 'Instale via npm com um único comando e comece a automatizar.' },
    ],
  },
  'social-media-cli': {
    slug: 'social-media-cli',
    title: 'Social Media CLI',
    headline: 'Social Media CLI',
    description: 'Linha de comando para publicar em redes sociais. Publique do terminal sem escrever código, com agendamento, analytics e upload em comandos simples.',
    category: 'specialized',
    features: [
      { name: 'Publicar do terminal', desc: 'stackpost post --text "Hello" --platforms instagram,facebook' },
      { name: 'Agendar', desc: 'stackpost schedule --time "2026-08-27T10:00:00Z" para publicação futura.' },
      { name: 'Listar contas', desc: 'stackpost accounts list para ver todas as contas conectadas.' },
      { name: 'Analytics', desc: 'stackpost analytics --post abc123 para métricas de qualquer publicação.' },
      { name: 'Upload', desc: 'stackpost upload ./video.mp4 para enviar mídias antes de publicar.' },
      { name: 'npm package', desc: 'Instale via npm globalmente e use em qualquer projeto.' },
    ],
  },
  'claude-code-social-media': {
    slug: 'claude-code-social-media',
    title: 'Claude Code Social Media',
    headline: 'Claude Code + StackPost',
    description: 'Integre StackPost com Claude Code via MCP server. Crie, agende e analise posts direto do Claude, automatizando redes sociais com linguagem natural.',
    category: 'specialized',
    features: [
      { name: 'MCP server', desc: 'Model Context Protocol integration para comunicação nativa com Claude.' },
      { name: 'Claude Code', desc: 'Use Claude Code para publicar posts com comandos em linguagem natural.' },
      { name: 'Claude Desktop', desc: 'Use Claude Desktop para gerenciar redes sociais sem sair do app.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts e get_analytics prontas.' },
      { name: 'Setup em 1 comando', desc: 'npx stackpost mcp install claude para configuração instantânea.' },
    ],
  },
  'cursor-social-media': {
    slug: 'cursor-social-media',
    title: 'Cursor Social Media',
    headline: 'Cursor + StackPost',
    description: 'Integre StackPost com Cursor IDE via MCP server. Crie e agende posts direto do editor, com AI caption e analytics sem trocar de contexto.',
    category: 'specialized',
    features: [
      { name: 'MCP server', desc: 'Model Context Protocol integration para comunicação nativa com Cursor.' },
      { name: 'Cursor IDE', desc: 'Use Cursor para publicar posts sem sair do seu fluxo de desenvolvimento.' },
      { name: 'AI caption', desc: 'Gere captions com IA direto no editor, otimizadas por plataforma.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts e get_analytics prontas.' },
      { name: 'Setup em 1 comando', desc: 'npx stackpost mcp install cursor para configuração instantânea.' },
    ],
  },
};

export const auxPages: Record<string, SEOPageData> = {
  'platforms': {
    slug: 'platforms',
    title: 'Todas as Plataformas',
    headline: '15 plataformas suportadas',
    description: 'StackPost suporta Instagram, TikTok, YouTube, Facebook, LinkedIn, X, Threads, Pinterest, Reddit, Bluesky, Mastodon, Discord, Slack, Google Business e Snapchat.',
    category: 'api',
    features: [
      { name: 'Instagram', desc: 'Post, Reel, Story. Carousel ate 10 items. Meta Graph API.' },
      { name: 'TikTok', desc: 'Video e Photo Mode. Content API oficial.' },
      { name: 'YouTube', desc: 'Video e Shorts. Data API v3. Monetizacao.' },
      { name: 'Facebook', desc: 'Page post, Reel, Story. Meta Graph API.' },
      { name: 'LinkedIn', desc: 'Perfil e Company Page. Marketing API.' },
      { name: 'X / Twitter', desc: 'Tweet com midia. API v2.' },
      { name: 'Threads', desc: 'Texto, midia, poll, gif, link.' },
      { name: 'Pinterest', desc: 'Pin com board. API v5.' },
      { name: 'Reddit', desc: 'Text, link, midia, gallery.' },
      { name: 'Bluesky', desc: 'AT Protocol. Descentralizado.' },
      { name: 'Mastodon', desc: 'Instancia custom. Status.' },
      { name: 'Discord', desc: 'Webhook URL. 10 attachments.' },
      { name: 'Slack', desc: 'Webhook URL. 4 attachments.' },
      { name: 'Google Business', desc: 'STANDARD, EVENT, OFFER, ALERT.' },
      { name: 'Snapchat', desc: 'Story e Spotlight. Marketing API.' },
    ],
  },
  'errors': {
    slug: 'errors',
    title: 'API Error Reference',
    headline: 'API Error Reference',
    description: 'Referencia completa de erros da API do StackPost. errorsVerbose com code, userFacingMessage e isTransient.',
    category: 'api',
    features: [
      { name: 'errorsVerbose', desc: 'Todo erro retorna code, userFacingMessage e isTransient.' },
      { name: 'Error codes', desc: 'Codigos padronizados por plataforma e tipo.' },
      { name: 'isTransient', desc: 'Indica se o erro e temporario (retry) ou permanente.' },
      { name: 'Platform errors', desc: 'Meta:190 (token expired), Meta:368 (rate limited), etc.' },
      { name: 'Actionable context', desc: 'Erros faceis a debugar sem adivinhacao.' },
    ],
  },
  'multi-tenant-social-media-api': {
    slug: 'multi-tenant-social-media-api',
    title: 'Multi-Tenant Social Media API',
    headline: 'Multi-Tenant Social Media API',
    description: 'Modele clientes, equipes, marcas e localidades como workspaces separados. Cada tenant tem suas contas, posts e analytics.',
    category: 'api',
    features: [
      { name: 'Organizations', desc: 'Multi-tenancy. Cada org tem sua cota e billing.' },
      { name: 'Teams', desc: 'Times dentro de orgs. Permissoes por team.' },
      { name: 'Workspace separado', desc: 'Contas, posts, uploads, analytics e errors isolados.' },
      { name: 'RBAC', desc: 'Owner, admin, editor, viewer.' },
      { name: 'Audit log', desc: 'Todas as acoes registradas.' },
    ],
  },
  'white-label-social-media-api': {
    slug: 'white-label-social-media-api',
    title: 'White Label Social Media API',
    headline: 'White Label Social Media API',
    description: 'Power your own branded dashboard, client portal, approval flow, or embedded scheduler with StackPost.',
    category: 'api',
    features: [
      { name: 'Sua marca', desc: 'Dashboard com sua marca e identidade visual.' },
      { name: 'Client portal', desc: 'Portal de clientes white-label.' },
      { name: 'Approval flow', desc: 'Fluxo de aprovacao customizavel.' },
      { name: 'Embedded scheduler', desc: 'Agendador embutido no seu produto.' },
      { name: 'API-first', desc: 'Tudo via API. Voce monta a interface.' },
    ],
  },
  'upload-post-alternative': {
    slug: 'upload-post-alternative',
    title: 'Alternativa ao Upload-Post',
    headline: 'StackPost: a alternativa completa ao Upload-Post',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O Upload-Post é uma ferramenta visual de agendamento; o StackPost é API + interface + automação programável em um só lugar, com 15 plataformas, legendas com IA e multi-usuário com RBAC sem cobrança por seat.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: '114 endpoints documentados com OpenAPI 3.1 para automação total. O Upload-Post não expõe API pública.' },
      { name: '15 plataformas', desc: 'Cobertura ampla de canais em um único endpoint unificado. O Upload-Post suporta menos plataformas.' },
      { name: 'MCP server + CLI', desc: 'Agents de IA publicam posts via Model Context Protocol direto no terminal. O Upload-Post não oferece.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática e reprocessamento garantido. O Upload-Post não tem.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Upload-Post cobra por usuário.' },
      { name: 'Legendas com IA', desc: 'Geração de variações de copy com Nexus IA integrada. O Upload-Post tem IA básica.' },
      { name: 'Analytics com histórico indefinido', desc: 'Snapshot diário com gráfico de evolução das métricas. O Upload-Post retém dados por tempo limitado.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem variação cambial. O Upload-Post cobra em USD.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Upload-Post?', a: 'Sim. O StackPost vai além do agendamento visual: entrega API REST, MCP server, webhooks com replay e multi-usuário com RBAC, ideal para developers e times que precisam de automação e integração programável.' },
      { q: 'Posso migrar do Upload-Post?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração das suas contas, conteúdo e agendamentos passo a passo.' },
    ],
  },
};
