import { SEOPageData } from '@/components/SEOPage';

export const platformPages: Record<string, SEOPageData> = {
  'instagram-api': {
    slug: 'instagram-api',
    title: 'Instagram API',
    headline: 'Instagram API via StackPost',
    description: 'Publique posts, Reels e Stories no Instagram via API. Carousel ate 10 items, first comment automatico, Meta Graph API oficial.',
    category: 'platform',
    features: [
      { name: 'Post, Reel, Story', desc: 'Suporte completo aos 3 formatos do Instagram.' },
      { name: 'Carousel ate 10 items', desc: 'Multiplas imagens/videos em um unico post.' },
      { name: 'First comment', desc: 'Comente automaticamente apos publicar (max 2.200 chars).' },
      { name: 'OAuth via Meta', desc: 'Fluxo OAuth oficial da Meta. Set-channel obrigatorio.' },
      { name: 'Meta Graph API', desc: 'Integracao direta com a Graph API da Meta.' },
      { name: 'Audio + Locations + Tags', desc: 'Reels music, locations e business discovery.' },
    ],
    endpoints: [
      { method: 'POST', path: '/post', desc: 'Publicar no Instagram' },
      { method: 'POST', path: '/comment', desc: 'Comentar em posts' },
      { method: 'GET', path: '/analytics/post/raw', desc: 'Analytics crus' },
    ],
  },
  'tiktok-api': {
    slug: 'tiktok-api',
    title: 'TikTok API',
    headline: 'TikTok API via StackPost',
    description: 'Publique videos e Photo Mode no TikTok via API. Content API oficial, status REVIEW, musicSoundInfo e first comment.',
    category: 'platform',
    features: [
      { name: 'Video e Photo Mode', desc: 'Suporte aos 2 formatos do TikTok.' },
      { name: 'Photo Mode', desc: 'JPG/WebP only. PNG rejeitado.' },
      { name: 'Status REVIEW', desc: 'Re-check automatico do status de revisao.' },
      { name: 'musicSoundInfo', desc: 'CML trending list para musica.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 150 chars).' },
      { name: 'Content API oficial', desc: 'Integracao direta com TikTok Content API.' },
    ],
  },
  'facebook-api': {
    slug: 'facebook-api',
    title: 'Facebook API',
    headline: 'Facebook API via StackPost',
    description: 'Publique Page posts, Reels e Stories no Facebook via API. Meta Graph API, first comment ate 8.000 chars.',
    category: 'platform',
    features: [
      { name: 'Page post, Reel, Story', desc: 'Suporte completo aos formatos do Facebook.' },
      { name: '4 imagens ou 1 video', desc: 'Midia por post.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 8.000 chars).' },
      { name: 'OAuth Meta', desc: 'Selecione TODAS as Pages no OAuth.' },
      { name: 'Meta Graph API', desc: 'Integracao oficial Meta.' },
      { name: 'Auto Reply', desc: 'Resposta automatica a comentarios.' },
    ],
  },
  'youtube-api': {
    slug: 'youtube-api',
    title: 'YouTube API',
    headline: 'YouTube API via StackPost',
    description: 'Publique videos e Shorts no YouTube via API. Data API v3, madeForKids required, analytics com monetizacao.',
    category: 'platform',
    features: [
      { name: 'Video e Shorts', desc: 'Shorts auto-detectados por duracao.' },
      { name: 'madeForKids required', desc: 'Campo obrigatorio por COPPA.' },
      { name: 'Titulo 100 chars', desc: 'Description ate 5.000 chars.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 10.000 chars).' },
      { name: 'Analytics com monetizacao', desc: 'withBusinessScope + rawYoutubeAnalyticsEnabled.' },
      { name: 'Playlists', desc: 'CRUD de playlists e items.' },
    ],
  },
  'linkedin-api': {
    slug: 'linkedin-api',
    title: 'LinkedIn API',
    headline: 'LinkedIn API via StackPost',
    description: 'Publique no perfil e Company Pages do LinkedIn via API. Texto, midia, link, documento. Mentions e first comment.',
    category: 'platform',
    features: [
      { name: 'Perfil e Company Page', desc: 'Set-channel: perfil ou empresa.' },
      { name: 'Texto, midia, link, doc', desc: '10 midias ou 1 PDF por post.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 1.250 chars).' },
      { name: 'Mentions builder', desc: '/misc/linkedin/mentions/builder.' },
      { name: 'Marketing API', desc: 'Integracao oficial LinkedIn.' },
      { name: 'mediaTitle 200 chars', desc: 'Titulo de midia suportado.' },
    ],
  },
  'x-api': {
    slug: 'x-api',
    title: 'X API',
    headline: 'X (Twitter) API via StackPost',
    description: 'Publique tweets com midia via API v2. 4 imagens ou 1 video. Cobranca pre-paga por post.',
    category: 'platform',
    features: [
      { name: 'Tweet com midia', desc: '4 imagens ou 1 video por tweet.' },
      { name: 'Text 280 / 25.000 chars', desc: 'Limite de texto flexivel.' },
      { name: 'API v2', desc: 'Integracao oficial X API v2.' },
      { name: 'OAuth direto', desc: 'Sem set-channel.' },
      { name: 'Prepaid credits', desc: '$0.015/post, $0.20/post com link.' },
      { name: 'Sem first comment', desc: 'X nao suporta comment via API.' },
    ],
  },
  'threads-api': {
    slug: 'threads-api',
    title: 'Threads API',
    headline: 'Threads API via StackPost',
    description: 'Publique no Threads via API. Texto, midia, poll, gif, link. 10 imagens ou 1 video. First comment.',
    category: 'platform',
    features: [
      { name: 'Texto, midia, poll, gif, link', desc: 'Todos os formatos do Threads.' },
      { name: '10 imagens ou 1 video', desc: 'Multi-midia por post.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 500 chars).' },
      { name: 'OAuth direto', desc: 'Sem set-channel.' },
      { name: 'Meta API', desc: 'Integracao via Meta.' },
    ],
  },
  'pinterest-api': {
    slug: 'pinterest-api',
    title: 'Pinterest API',
    headline: 'Pinterest API via StackPost',
    description: 'Publique pins no Pinterest via API v5. Board required, 1 imagem ou video por pin.',
    category: 'platform',
    features: [
      { name: 'Pin com board', desc: 'BoardName required.' },
      { name: '1 imagem ou video', desc: 'Midia unica por pin.' },
      { name: 'API v5', desc: 'Integracao oficial Pinterest API v5.' },
      { name: 'OAuth sem set-channel', desc: 'Boards via refresh.' },
      { name: 'Sem first comment', desc: 'Pinterest nao suporta.' },
    ],
  },
  'reddit-api': {
    slug: 'reddit-api',
    title: 'Reddit API',
    headline: 'Reddit API via StackPost',
    description: 'Publique text, link, midia e gallery no Reddit via API. Subreddit required, post-requirements check.',
    category: 'platform',
    features: [
      { name: 'Text, link, midia, gallery', desc: 'Todos os formatos do Reddit.' },
      { name: 'Subreddit required', desc: 'sr obrigatorio.' },
      { name: 'Post-requirements', desc: '/misc/reddit/post-requirements ANTES de postar.' },
      { name: 'Subreddit flairs', desc: '/misc/reddit/subreddit-flairs.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 10.000 chars).' },
      { name: 'Text 300, description 30.000', desc: 'Limites de texto.' },
    ],
  },
  'bluesky-api': {
    slug: 'bluesky-api',
    title: 'Bluesky API',
    headline: 'Bluesky API via StackPost',
    description: 'Publique no Bluesky via AT Protocol. Texto, midia, link card, quote. 4 midias, first comment.',
    category: 'platform',
    features: [
      { name: 'AT Protocol', desc: 'Protocolo aberto e descentralizado.' },
      { name: 'Texto, midia, link card, quote', desc: 'Todos os formatos.' },
      { name: '4 midias', desc: 'Multi-midia por post.' },
      { name: 'serverUrl opcional', desc: 'Default bsky.social. Instancia custom suportada.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 300 chars).' },
      { name: 'Text 300 chars', desc: 'Limite de texto.' },
    ],
  },
  'mastodon-api': {
    slug: 'mastodon-api',
    title: 'Mastodon API',
    headline: 'Mastodon API via StackPost',
    description: 'Publique no Mastodon via API. Instancia custom, 4 midias, privacy, spoiler text. First comment.',
    category: 'platform',
    features: [
      { name: 'Instancia custom', desc: 'serverUrl obrigatorio. Suporte a qualquer instancia.' },
      { name: '4 midias', desc: 'Multi-midia por status.' },
      { name: 'Privacy + spoiler', desc: 'Controle de privacidade e spoiler text.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 500 chars).' },
      { name: 'Status', desc: 'Publicacao de status com midia.' },
    ],
  },
  'slack-api': {
    slug: 'slack-api',
    title: 'Slack API',
    headline: 'Slack API via StackPost',
    description: 'Publique mensagens no Slack via webhook URL. 4 attachments, text ate 30.000 chars, first comment.',
    category: 'platform',
    features: [
      { name: 'Webhook URL', desc: 'Integracao via webhook do Slack.' },
      { name: 'channelId required', desc: 'Canal especifico.' },
      { name: '4 attachments', desc: 'Anexos por mensagem.' },
      { name: 'Text 30.000 chars', desc: 'Limite de texto generoso.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 30.000 chars).' },
    ],
  },
  'discord-api': {
    slug: 'discord-api',
    title: 'Discord API',
    headline: 'Discord API via StackPost',
    description: 'Publique mensagens no Discord via webhook URL. 10 attachments, text ate 2.000 chars, first comment.',
    category: 'platform',
    features: [
      { name: 'Webhook URL', desc: 'Integracao via webhook do Discord.' },
      { name: 'channelId required', desc: 'Canal especifico.' },
      { name: '10 attachments', desc: 'Anexos por mensagem.' },
      { name: 'Text 2.000 chars', desc: 'Limite de texto.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 2.000 chars).' },
    ],
  },
  'google-business-api': {
    slug: 'google-business-api',
    title: 'Google Business Profile API',
    headline: 'Google Business API via StackPost',
    description: 'Publique posts no Google Business Profile via API. STANDARD, EVENT, OFFER, ALERT. Location management completo.',
    category: 'platform',
    features: [
      { name: 'STANDARD, EVENT, OFFER, ALERT', desc: '4 tipos de post.' },
      { name: 'Location management', desc: 'CRUD location, attributes, categories, food-menus, hours.' },
      { name: 'set-channel: location', desc: 'Local especifico.' },
      { name: '1 imagem, text 1.500', desc: 'Midia e texto por post.' },
      { name: 'Reviews API', desc: 'Import e resposta de reviews.' },
      { name: 'Sem first comment', desc: 'GBP nao suporta.' },
    ],
  },
  'snapchat-api': {
    slug: 'snapchat-api',
    title: 'Snapchat API',
    headline: 'Snapchat API via StackPost',
    description: 'Publique Stories e Spotlights no Snapchat via Marketing API. Public Profile, 1 midia por post.',
    category: 'platform',
    features: [
      { name: 'Story e Spotlight', desc: '2 formatos suportados.' },
      { name: 'Public Profile', desc: 'OAuth via Public Profile.' },
      { name: '1 midia por post', desc: 'Midia unica.' },
      { name: 'Marketing API', desc: 'Integracao oficial Snapchat.' },
      { name: 'Sem first comment', desc: 'Snapchat nao suporta.' },
    ],
  },
};

export const apiPages: Record<string, SEOPageData> = {
  'social-media-api': {
    slug: 'social-media-api',
    title: 'Social Media API',
    headline: 'Social Media API unificada',
    description: 'Uma API para 15 plataformas de redes sociais. Publicacao paralela, agendamento, analytics, comentarios e mais.',
    category: 'api',
    features: [
      { name: '15 plataformas', desc: 'Instagram, TikTok, YouTube, Facebook, LinkedIn, X, Threads, Pinterest, Reddit, Bluesky, Mastodon, Discord, Slack, Google Business, Snapchat.' },
      { name: 'Publicacao paralela', desc: 'Promise.allSettled. Falha em uma nao afeta outras.' },
      { name: '114 endpoints', desc: 'API REST completa. OpenAPI 3.1.' },
      { name: 'API Key auth', desc: 'Header x-api-key. Padrao Stripe-like.' },
      { name: 'Rate limit 3 camadas', desc: '100/1s, 500/10s, 2000/60s.' },
      { name: 'Webhooks', desc: '9 eventos. HMAC-SHA256. Replay suportado.' },
    ],
  },
  'posting-api': {
    slug: 'posting-api',
    title: 'Posting API',
    headline: 'Posting API para redes sociais',
    description: 'Publique em 15 plataformas com uma unica request. Validacao por plataforma, first comment, rascunho e agendamento.',
    category: 'api',
    features: [
      { name: 'POST /post', desc: 'Endpoint unificado. Valida regras por plataforma.' },
      { name: 'DRAFT ou SCHEDULED', desc: 'Salve rascunho ou agende para depois.' },
      { name: 'First comment', desc: 'Comente automaticamente apos publicar.' },
      { name: 'Idempotency-Key', desc: 'Preveni duplicacao em retries.' },
      { name: 'errorsVerbose', desc: 'Erros padronizados com code, userFacingMessage, isTransient.' },
      { name: 'Retry transient', desc: '3 retries, backoff 30s/90s/270s.' },
    ],
  },
  'scheduling-api': {
    slug: 'scheduling-api',
    title: 'Scheduling API',
    headline: 'Scheduling API para redes sociais',
    description: 'Agende posts para qualquer horario. Cron job processa no momento certo. Best-time-to-post com ML.',
    category: 'api',
    features: [
      { name: 'Agendamento', desc: 'postDate no futuro. Cron job processa.' },
      { name: 'Best-time-to-post', desc: 'ML sugere top 3 horarios por conta.' },
      { name: 'Calendar view', desc: 'Calendario de posts agendados.' },
      { name: 'Drag-and-drop', desc: 'Reagende arrastando no calendario.' },
      { name: 'Approval workflow', desc: 'DRAFT -> REVIEW -> APPROVED -> SCHEDULED.' },
    ],
  },
  'media-upload-api': {
    slug: 'media-upload-api',
    title: 'Media Upload API',
    headline: 'Media Upload API',
    description: '4 metodos de upload: simple, direct, multipart, from-url. tus protocol. Cloudflare R2 com zero egress.',
    category: 'api',
    features: [
      { name: 'Simple upload', desc: 'Multipart/form-data, 90 MB.' },
      { name: 'Direct upload', desc: 'Presigned URL R2, 30 min expiry.' },
      { name: 'Multipart resumable', desc: 'Chunks de 64 MiB, 6h expiry, 10.000 parts max.' },
      { name: 'Upload from URL', desc: 'Importe de qualquer URL, 1 GB max.' },
      { name: 'tus protocol', desc: 'Padrao da industria. Bibliotecas em todas linguagens.' },
      { name: 'Cloudflare R2', desc: 'S3-compativel. ZERO egress fee.' },
    ],
  },
  'bulk-posting': {
    slug: 'bulk-posting',
    title: 'Bulk Posting API',
    headline: 'Bulk Posting API',
    description: 'Publique em lote via CSV ou API. Centenas de posts por request. Resultados por linha.',
    category: 'api',
    features: [
      { name: 'CSV bulk import', desc: 'POST /post-csv-import. Resultados por linha.' },
      { name: 'API bulk', desc: 'POST /post/bulk. Centenas de posts por request.' },
      { name: 'Hard cap 100 posts', desc: 'Por request. Acima disso, fracionar.' },
      { name: 'Resultados detalhados', desc: 'Sucesso/erro por linha.' },
    ],
  },
  'post-history-api': {
    slug: 'post-history-api',
    title: 'Post History API',
    headline: 'Post History API',
    description: 'Importe historico de posts de 15 plataformas. Limites por plano. Retencao 30 dias.',
    category: 'api',
    features: [
      { name: '15 plataformas', desc: 'Importe de todas as plataformas suportadas.' },
      { name: 'Async import', desc: 'POST /post-history-import. Worker processa.' },
      { name: 'Limites por plano', desc: 'FREE 5 / STARTER 50 / GROWTH 200 / SCALE 500 / BUSINESS 1.000 por conta/mes.' },
      { name: 'Hard cap 100', desc: 'Posts por request.' },
    ],
  },
  'comments-api': {
    slug: 'comments-api',
    title: 'Comments API',
    headline: 'Comments API',
    description: 'Poste e importe comentarios em 11 plataformas via API unificada. Reply automation e comment-to-DM.',
    category: 'api',
    features: [
      { name: 'POST /comment', desc: 'Comente em 11 plataformas.' },
      { name: 'POST /comment/import', desc: 'Importe comentarios de 9 plataformas.' },
      { name: 'Reply automation', desc: 'Responda comentarios automaticamente.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em DM no Instagram e Facebook.' },
      { name: 'Limites por plano', desc: 'FREE 25 / STARTER 100 / GROWTH 400 / SCALE 1.000 / BUSINESS 2.000 por post.' },
    ],
  },
  'analytics-api': {
    slug: 'analytics-api',
    title: 'Analytics API',
    headline: 'Analytics API',
    description: 'Metricas normalizadas e raw analytics por plataforma. Historico indefinido. YouTube monetizacao.',
    category: 'api',
    features: [
      { name: 'Metricas normalizadas', desc: 'Impressions, views, likes, comments, shares, saves.' },
      { name: 'Raw analytics', desc: 'Dados crus por plataforma.' },
      { name: 'Historico indefinido', desc: 'Cron job diario salva snapshot. Grafico de evolucao.' },
      { name: 'YouTube monetizacao', desc: 'withBusinessScope + rawYoutubeAnalyticsEnabled.' },
      { name: 'Force refresh', desc: 'POST /analytics/post/force. Rate limit por team.' },
      { name: 'Retencao 30 dias', desc: 'Configuravel para indefinido no StackPost.' },
    ],
  },
  'first-comment-api': {
    slug: 'first-comment-api',
    title: 'First Comment API',
    headline: 'First Comment API',
    description: 'Comente automaticamente apos publicar. Suporte por plataforma com limites especificos.',
    category: 'api',
    features: [
      { name: 'Comentario automatico', desc: 'Agendado apos sucesso da publicacao.' },
      { name: 'Limites por plataforma', desc: 'Instagram 2.200, LinkedIn 1.250, TikTok 150, etc.' },
      { name: 'Suporte amplo', desc: '12 das 15 plataformas suportam first comment.' },
    ],
  },
  'unified-api': {
    slug: 'unified-api',
    title: 'Unified API',
    headline: 'Unified Social Media API',
    description: 'Uma integracao, 15 plataformas. Input unificado, sistema adapta para cada rede.',
    category: 'api',
    features: [
      { name: 'Input unificado', desc: 'text, media, hashtags, link.' },
      { name: 'Cross-post adaptativo', desc: 'Sistema gera data.PLATFORM por plataforma.' },
      { name: 'Edicao antes de publicar', desc: 'Usuario edita cada versao.' },
      { name: '15 plataformas', desc: 'Uma integracao para todas.' },
    ],
  },
};

export const comparisonPages: Record<string, SEOPageData> = {
  'ayrshare-alternative': {
    slug: 'ayrshare-alternative',
    title: 'Ayrshare Alternative',
    headline: 'StackPost: a melhor alternativa ao Ayrshare',
    description: 'API de redes sociais developer-first com 15 plataformas, MCP server, legendas com IA, A/B testing e multi-usuário com RBAC — sem cobrança por seat e com preços em reais.',
    category: 'comparison',
    features: [
      { name: '15 plataformas', desc: 'Mesma cobertura do Ayrshare em um único endpoint REST.' },
      { name: 'MCP server', desc: 'Agents de IA publicam posts via Model Context Protocol. O Ayrshare não oferece.' },
      { name: 'Legendas com IA', desc: 'Integração nativa com Nexus IA gera variações de copy. O Ayrshare não tem.' },
      { name: 'Analytics ilimitado', desc: 'O Ayrshare retém 30 dias; o StackPost guarda o histórico indefinidamente.' },
      { name: 'Multi-usuário com RBAC', desc: 'O Ayrshare cobra por seat; o StackPost inclui em todos os planos.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago. O Ayrshare cobra em USD com IOF.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Ayrshare?', a: 'Sim. O StackPost é uma API developer-first para times que precisam de uma integração única entre todas as principais plataformas, com preços transparentes por uso e sem taxas por usuário.' },
      { q: 'Posso migrar do Ayrshare?', a: 'Sim. A API do StackPost segue padrões REST similares e nossa equipe acompanha a migração passo a passo.' },
    ],
  },
  'zernio-alternative': {
    slug: 'zernio-alternative',
    title: 'Alternativa ao Zernio',
    headline: 'StackPost: a alternativa completa ao Zernio',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. Contas sociais ilimitadas em todos os planos pagos e cobrança por uso de API — não por conta. O Zernio cobra por conta conectada; o StackPost inclui contas ilimitadas e ainda entrega automação programável.',
    category: 'comparison',
    features: [
      { name: 'Contas ilimitadas', desc: 'Todos os planos pagos incluem contas sociais ilimitadas. O Zernio cobra por conta conectada, encarecendo a operação conforme a equipe cresce.' },
      { name: 'API REST completa', desc: '114 endpoints documentados com OpenAPI 3.1. O Zernio não expõe API pública para automação.' },
      { name: 'MCP server + CLI', desc: 'Agents de IA publicam posts via Model Context Protocol direto no terminal. O Zernio não oferece.' },
      { name: 'A/B testing de conteúdo', desc: 'Teste variações de legenda e mensure o desempenho de cada versão. O Zernio não tem.' },
      { name: 'Best-time-to-post com ML', desc: 'Sugestão dos 3 melhores horários por conta com machine learning. O Zernio não tem.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem variação cambial. O Zernio cobra em USD.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Zernio?', a: 'Sim. O StackPost vai além do agendamento: entrega API REST, MCP server, A/B testing e contas ilimitadas em todos os planos pagos, ideal para developers e times que precisam de automação e integração programável sem custos por conta.' },
      { q: 'Posso migrar do Zernio?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração das suas contas, conteúdo e agendamentos passo a passo.' },
    ],
  },
  'postiz-alternative': {
    slug: 'postiz-alternative',
    title: 'Alternativa ao Postiz',
    headline: 'StackPost: a alternativa completa ao Postiz',
    description: 'Plataforma developer-first com API REST de 114 endpoints, dashboard e MCP server. O Postiz é uma ferramenta visual de agendamento — o StackPost é API + interface + automação programável em um só lugar.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: '114 endpoints documentados com OpenAPI 3.1. O Postiz não expõe API pública.' },
      { name: 'MCP server', desc: 'Agents de IA publicam posts via Model Context Protocol. O Postiz não oferece.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática. O Postiz não tem.' },
      { name: 'SDK + CLI', desc: 'Bibliotecas em TypeScript, Python e Go. O Postiz não fornece.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Postiz tem planos limitados.' },
      { name: 'Analytics com histórico', desc: 'Retenção indefinida de métricas. O Postiz não guarda histórico.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Postiz?', a: 'Sim. O StackPost vai além do agendamento visual: entrega API REST, MCP server, webhooks e multi-usuário com RBAC, ideal para developers e times que precisam de automação e integração programável.' },
      { q: 'Posso migrar do Postiz?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
  'metricool-alternative': {
    slug: 'metricool-alternative',
    title: 'Alternativa ao Metricool',
    headline: 'StackPost: a alternativa completa ao Metricool',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O Metricool é só dashboard — o StackPost é API + interface + automação em um só lugar.',
    category: 'comparison',
    features: [
      { name: 'API REST pública', desc: 'Integre e automatize via HTTP. O Metricool não oferece API pública.' },
      { name: 'MCP server + CLI', desc: 'Automação com agentes de IA direto no terminal. O Metricool não tem.' },
      { name: 'Webhooks com replay', desc: 'Eventos em tempo real e reprocessamento garantido. O Metricool não tem.' },
      { name: 'A/B testing de conteúdo', desc: 'Teste variações de posts e mensure o desempenho. O Metricool não tem.' },
      { name: 'Legendas com IA', desc: 'Geração de copy com Nexus IA integrada. O Metricool não tem.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão.' },
    ],
  },
  'publer-alternative': {
    slug: 'publer-alternative',
    title: 'Alternativa ao Publer',
    headline: 'StackPost: a alternativa completa ao Publer',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O Publer é apenas um dashboard de agendamento — o StackPost é API + interface + automação para developers e times.',
    category: 'comparison',
    features: [
      { name: 'API REST pública', desc: 'Integre e automatize via HTTP. O Publer não oferece API pública.' },
      { name: 'MCP server', desc: 'Agents de IA publicam via Model Context Protocol. O Publer não tem.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática. O Publer não tem.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Publer cobra por usuário.' },
      { name: 'Analytics com histórico', desc: 'Retenção indefinida de métricas. O Publer limita o histórico.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão cambial.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Publer?', a: 'Sim. O StackPost entrega API REST, MCP server, webhooks e multi-usuário com RBAC — recursos que o Publer não oferece — ideal para developers e times que precisam de automação programável.' },
      { q: 'Posso migrar do Publer?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
  'buffer-alternative': {
    slug: 'buffer-alternative',
    title: 'Alternativa ao Buffer',
    headline: 'StackPost: a alternativa ao Buffer para developers e times',
    description: 'API developer-first com 15 plataformas, MCP server e A/B testing. O Buffer é uma ferramenta simples de agendamento — o StackPost é uma plataforma completa de publicação e automação.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: 'Automação total via HTTP. O Buffer tem API limitada.' },
      { name: '15 plataformas', desc: 'Cobertura ampla de canais. O Buffer suporta menos.' },
      { name: 'MCP server', desc: 'Integração com agentes de IA. O Buffer não tem.' },
      { name: 'A/B testing', desc: 'Teste variações de conteúdo com dados. O Buffer não tem.' },
      { name: 'Legendas com IA', desc: 'Geração de copy com Nexus IA. O Buffer tem IA básica.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão.' },
    ],
  },
  'socialpilot-alternative': {
    slug: 'socialpilot-alternative',
    title: 'Alternativa ao SocialPilot',
    headline: 'StackPost: a alternativa completa ao SocialPilot',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O SocialPilot é apenas um dashboard de agendamento — o StackPost é API + interface + automação para developers e times.',
    category: 'comparison',
    features: [
      { name: 'API REST pública', desc: 'Integre e automatize via HTTP. O SocialPilot não oferece API pública.' },
      { name: 'MCP server + CLI', desc: 'Automação com agentes de IA direto no terminal. O SocialPilot não tem.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática. O SocialPilot não tem.' },
      { name: 'A/B testing de conteúdo', desc: 'Teste variações de posts e mensure o desempenho. O SocialPilot não tem.' },
      { name: 'Analytics com histórico', desc: 'Retenção indefinida de métricas. O SocialPilot limita o histórico.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem conversão cambial.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao SocialPilot?', a: 'Sim. O StackPost entrega API REST, MCP server, webhooks e A/B testing — recursos que o SocialPilot não oferece — ideal para developers e times que precisam de automação programável.' },
      { q: 'Posso migrar do SocialPilot?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
  'blotato-alternative': {
    slug: 'blotato-alternative',
    title: 'Blotato Alternative',
    headline: 'StackPost: a melhor alternativa ao Blotato',
    description: 'API developer-first com 15 plataformas, MCP server, webhooks com replay e multi-usuário com RBAC. O Blotato é uma ferramenta simples de agendamento; o StackPost é uma plataforma completa para developers e times.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: '114 endpoints documentados. O Blotato não expõe API pública.' },
      { name: '15 plataformas', desc: 'Cobertura completa em um único endpoint. O Blotato tem menos.' },
      { name: 'MCP server', desc: 'Agents de IA publicam via Model Context Protocol. O Blotato não oferece.' },
      { name: 'Webhooks com replay', desc: '9 eventos com retentativa automática. O Blotato não tem.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Blotato não tem.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem variação cambial.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Blotato?', a: 'Sim. O StackPost vai além do agendamento: entrega API REST, MCP server, webhooks e multi-usuário com RBAC, ideal para developers e times que precisam de automação e integração programável.' },
      { q: 'Posso migrar do Blotato?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração do seu conteúdo e agendamentos.' },
    ],
  },
};

export const specializedPages: Record<string, SEOPageData> = {
  'instagram-auto-reply': {
    slug: 'instagram-auto-reply',
    title: 'Instagram Auto Reply API',
    headline: 'Instagram Auto Reply API',
    description: 'Resposta automatica a comentarios no Instagram. Configure regras e o bot responde por voce.',
    category: 'specialized',
    features: [
      { name: 'Auto-resposta', desc: 'Responda comentarios automaticamente.' },
      { name: 'Regras customizaveis', desc: 'Por palavra-chave, horario, tipo.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em DM.' },
    ],
  },
  'facebook-auto-reply': {
    slug: 'facebook-auto-reply',
    title: 'Facebook Auto Reply API',
    headline: 'Facebook Auto Reply API',
    description: 'Resposta automatica a comentarios no Facebook. Configure regras e o bot responde por voce.',
    category: 'specialized',
    features: [
      { name: 'Auto-resposta', desc: 'Responda comentarios automaticamente.' },
      { name: 'Regras customizaveis', desc: 'Por palavra-chave, horario, tipo.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em DM.' },
    ],
  },
  'meta-automation': {
    slug: 'meta-automation',
    title: 'Meta Automation API',
    headline: 'Meta Automation API',
    description: 'Automacao completa para Instagram e Facebook. Auto-reply, comment-to-DM, post scheduling.',
    category: 'specialized',
    features: [
      { name: 'Instagram + Facebook', desc: 'Automacao para ambas as plataformas Meta.' },
      { name: 'Auto-reply', desc: 'Resposta automatica.' },
      { name: 'Comment to DM', desc: 'Conversao em DM.' },
      { name: 'Post scheduling', desc: 'Agendamento.' },
    ],
  },
  'social-dm-api': {
    slug: 'social-dm-api',
    title: 'Social DM API',
    headline: 'Social DM API',
    description: 'Envie e gerencie mensagens diretas via API. Instagram DM, Messenger e mais.',
    category: 'specialized',
    features: [
      { name: 'Instagram DM', desc: 'Direct messages no Instagram.' },
      { name: 'Messenger', desc: 'Facebook Messenger.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em DM.' },
    ],
  },
  'comment-to-dm': {
    slug: 'comment-to-dm',
    title: 'Comment to DM API',
    headline: 'Comment to DM API',
    description: 'Converta comentarios em mensagens diretas automaticamente. Instagram e Facebook.',
    category: 'specialized',
    features: [
      { name: 'Instagram', desc: 'Comentario -> DM no Instagram.' },
      { name: 'Facebook', desc: 'Comentario -> DM no Facebook.' },
      { name: 'Automacao', desc: 'Sem intervencao manual.' },
    ],
  },
  'social-ads-api': {
    slug: 'social-ads-api',
    title: 'Social Ads API',
    headline: 'Social Ads API',
    description: 'Gerencie anuncios em redes sociais via API. Meta Ads, Google Ads e mais.',
    category: 'specialized',
    features: [
      { name: 'Meta Ads', desc: 'Facebook e Instagram Ads.' },
      { name: 'Google Ads', desc: 'Google Ads integration.' },
      { name: 'Multi-plataforma', desc: 'Uma API para todos.' },
    ],
  },
  'api-for-saas': {
    slug: 'api-for-saas',
    title: 'API for SaaS',
    headline: 'Social Media API for SaaS',
    description: 'Integre redes sociais no seu SaaS via API. White-label, multi-tenancy, webhooks.',
    category: 'specialized',
    features: [
      { name: 'White-label', desc: 'Sua marca, sua interface.' },
      { name: 'Multi-tenancy', desc: 'Cada cliente seu tem sua propria org.' },
      { name: 'Webhooks', desc: '9 eventos. HMAC-SHA256.' },
      { name: 'Rate limit', desc: '3 camadas. Headers X-RateLimit-*.' },
    ],
  },
  'api-for-ai-agents': {
    slug: 'api-for-ai-agents',
    title: 'API for AI Agents',
    headline: 'Social Media API for AI Agents',
    description: 'MCP server para Claude, Cursor e AI agents. Crie, agende e analise posts via tools.',
    category: 'specialized',
    features: [
      { name: 'MCP server', desc: 'Model Context Protocol. Claude, Cursor.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts, get_analytics, upload_media.' },
      { name: 'stdio + HTTP', desc: 'Dois modos de operacao.' },
      { name: 'AI caption', desc: 'Nexus IA gera 3-5 variacoes.' },
    ],
  },
  'instagram-music-api': {
    slug: 'instagram-music-api',
    title: 'Instagram Music API',
    headline: 'Instagram Music API',
    description: 'Acesse a biblioteca de musicas do Instagram para Reels. Busque, liste e adicione musicas trending aos seus Reels via API.',
    category: 'specialized',
    features: [
      { name: 'Biblioteca de musicas', desc: 'Acesse o catalogo completo de musicas do Instagram.' },
      { name: 'Trending', desc: 'Liste as musicas em alta para Reels.' },
      { name: 'Busca por nome', desc: 'Encontre musicas por nome, artista ou genero.' },
      { name: 'Adicao a Reels', desc: 'Adicione musicas aos seus Reels via API.' },
      { name: 'Endpoint dedicado', desc: '/misc/instagram/audio.' },
    ],
  },
  'tiktok-music-api': {
    slug: 'tiktok-music-api',
    title: 'TikTok Music API',
    headline: 'TikTok Music API',
    description: 'Acesse a CML (Commercial Music Library) do TikTok. Liste musicas trending e adicione aos seus videos via API.',
    category: 'specialized',
    features: [
      { name: 'CML trending list', desc: 'Commercial Music Library do TikTok.' },
      { name: 'Musicas em alta', desc: 'Liste as musicas trending do momento.' },
      { name: 'Busca por nome', desc: 'Encontre musicas por nome ou artista.' },
      { name: 'Adicao a videos', desc: 'Adicione musicas aos seus videos via API.' },
      { name: 'Endpoint dedicado', desc: '/misc/tiktok/cml/trending-list.' },
    ],
  },
  'tiktok-content-posting-api': {
    slug: 'tiktok-content-posting-api',
    title: 'TikTok Content Posting API',
    headline: 'TikTok Content Posting API',
    description: 'Publique videos e Photo Mode no TikTok via Content API oficial. Status REVIEW, musicSoundInfo e first comment.',
    category: 'specialized',
    features: [
      { name: 'Content API oficial', desc: 'Integracao direta com TikTok Content Posting API.' },
      { name: 'Video e Photo Mode', desc: 'Suporte aos 2 formatos.' },
      { name: 'Status REVIEW', desc: 'Re-check automatico do status de revisao.' },
      { name: 'musicSoundInfo', desc: 'Adicione musicas da CML.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 150 chars).' },
    ],
  },
  'instagram-comments-api': {
    slug: 'instagram-comments-api',
    title: 'Instagram Comments API',
    headline: 'Instagram Comments API',
    description: 'Leia, responda e gerencie comentarios no Instagram via API. Suporte completo a comentarios de feed e Reels.',
    category: 'specialized',
    features: [
      { name: 'Ler comentarios', desc: 'Liste comentarios de posts e Reels.' },
      { name: 'Responder', desc: 'Responda comentarios via API.' },
      { name: 'Gerenciar', desc: 'Delete e modere comentarios.' },
      { name: 'Auto-reply', desc: 'Resposta automatica por regras.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em DM.' },
    ],
  },
  'facebook-comments-api': {
    slug: 'facebook-comments-api',
    title: 'Facebook Comments API',
    headline: 'Facebook Comments API',
    description: 'Leia, responda e gerencie comentarios no Facebook Pages via API. Suporte completo a moderacao.',
    category: 'specialized',
    features: [
      { name: 'Ler comentarios', desc: 'Liste comentarios de Page posts.' },
      { name: 'Responder', desc: 'Responda comentarios via API.' },
      { name: 'Gerenciar', desc: 'Delete e modere comentarios.' },
      { name: 'Auto-reply', desc: 'Resposta automatica por regras.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em Messenger.' },
    ],
  },
  'youtube-upload-api': {
    slug: 'youtube-upload-api',
    title: 'YouTube Upload API',
    headline: 'YouTube Upload API',
    description: 'Upload de videos para YouTube via Data API v3. Suporte a videos longos e Shorts, com madeForKids e thumbnails.',
    category: 'specialized',
    features: [
      { name: 'Data API v3', desc: 'Integracao oficial YouTube Data API v3.' },
      { name: 'Videos longos e Shorts', desc: 'Suporte completo. Shorts auto-detectados.' },
      { name: 'madeForKids', desc: 'Campo obrigatorio por COPPA.' },
      { name: 'Thumbnails', desc: 'Upload e gerenciamento de thumbnails.' },
      { name: 'Playlists', desc: 'CRUD de playlists e items.' },
    ],
  },
  'linkedin-company-page-api': {
    slug: 'linkedin-company-page-api',
    title: 'LinkedIn Company Page API',
    headline: 'LinkedIn Company Page API',
    description: 'Gerencie Company Pages do LinkedIn via API. Publique como empresa, mencione e analise performance.',
    category: 'specialized',
    features: [
      { name: 'Publicar como empresa', desc: 'Post em nome da Company Page.' },
      { name: 'Mentions builder', desc: '/misc/linkedin/mentions/builder.' },
      { name: 'Multi-midia', desc: '10 midias ou 1 PDF por post.' },
      { name: 'First comment', desc: 'Comente apos publicar (max 1.250 chars).' },
      { name: 'Marketing API', desc: 'Integracao oficial LinkedIn Marketing API.' },
    ],
  },
  'google-business-profile-reviews-api': {
    slug: 'google-business-profile-reviews-api',
    title: 'GBP Reviews API',
    headline: 'Google Business Profile Reviews API',
    description: 'Importe e responda reviews do Google Business Profile via API. Gerencie reputacao online.',
    category: 'specialized',
    features: [
      { name: 'Importar reviews', desc: 'Importe reviews do Google Business Profile.' },
      { name: 'Responder reviews', desc: 'Responda reviews via API.' },
      { name: 'Rating', desc: 'Acesse ratings e distribuicao de estrelas.' },
      { name: 'Multi-location', desc: 'Reviews de multiplas localidades.' },
    ],
  },
  'google-business-profile-posts-api': {
    slug: 'google-business-profile-posts-api',
    title: 'GBP Posts API',
    headline: 'Google Business Profile Posts API',
    description: 'Publique posts no Google Business Profile via API. STANDARD, EVENT, OFFER, ALERT com location management.',
    category: 'specialized',
    features: [
      { name: '4 tipos de post', desc: 'STANDARD, EVENT, OFFER, ALERT.' },
      { name: 'Location management', desc: 'CRUD de locations, attributes, categories.' },
      { name: 'Food menus', desc: 'Gerencie cardapios via API.' },
      { name: 'Hours', desc: 'Horarios de funcionamento.' },
      { name: 'Service list', desc: 'Lista de servicos.' },
    ],
  },
  'meta-app-review-rejected': {
    slug: 'meta-app-review-rejected',
    title: 'Meta App Review',
    headline: 'Meta App Review Guide',
    description: 'Guia para passar na revisao de apps da Meta. Erros comuns de rejeicao e como resolver cada um.',
    category: 'specialized',
    features: [
      { name: 'Erros comuns', desc: 'Lista de motivos de rejeicao mais frequentes.' },
      { name: 'Como resolver', desc: 'Passo a passo para cada tipo de rejeicao.' },
      { name: 'Permissoes', desc: 'Quais permissoes solicitar e justificar.' },
      { name: 'App Review', desc: 'Processo de revisao da Meta.' },
      { name: 'Best practices', desc: 'Como estruturar o app para aprovacao.' },
    ],
  },
  'instagram-dm-api': {
    slug: 'instagram-dm-api',
    title: 'Instagram DM API',
    headline: 'Instagram DM API',
    description: 'Envie e gerencie mensagens diretas no Instagram via API. Integracao com Instagram Messaging API.',
    category: 'specialized',
    features: [
      { name: 'Enviar DMs', desc: 'Mensagens diretas via API.' },
      { name: 'Ler DMs', desc: 'Liste e leia conversas.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em DM automaticamente.' },
      { name: 'Auto-reply', desc: 'Resposta automatica a DMs.' },
      { name: 'Webhooks', desc: 'Notificacao de novas DMs.' },
    ],
  },
  'facebook-messenger-api': {
    slug: 'facebook-messenger-api',
    title: 'Messenger API',
    headline: 'Facebook Messenger API',
    description: 'Envie e gerencie mensagens no Facebook Messenger via API. Integracao com Messenger Platform.',
    category: 'specialized',
    features: [
      { name: 'Enviar mensagens', desc: 'Mensagens via Messenger Platform.' },
      { name: 'Ler conversas', desc: 'Liste e leia conversas.' },
      { name: 'Comment to DM', desc: 'Converta comentarios em Messenger.' },
      { name: 'Auto-reply', desc: 'Resposta automatica.' },
      { name: 'Webhooks', desc: 'Notificacao de novas mensagens.' },
    ],
  },
  'meta-ads-api': {
    slug: 'meta-ads-api',
    title: 'Meta Ads API',
    headline: 'Meta Ads API',
    description: 'Gerencie anuncios no Facebook e Instagram via Meta Marketing API. Campanhas, ad sets, ads e relatorios.',
    category: 'specialized',
    features: [
      { name: 'Campanhas', desc: 'CRUD de campanhas via Meta Marketing API.' },
      { name: 'Ad sets', desc: 'Gerencie conjuntos de anuncios.' },
      { name: 'Ads', desc: 'Crie e edite anuncios.' },
      { name: 'Relatorios', desc: 'Performance e metricas de anuncios.' },
      { name: 'Audiences', desc: 'Custom e lookalike audiences.' },
    ],
  },
  'google-ads-api': {
    slug: 'google-ads-api',
    title: 'Google Ads API',
    headline: 'Google Ads API',
    description: 'Gerencie anuncios no Google via Google Ads API. Campanhas Search, Display, YouTube e Shopping.',
    category: 'specialized',
    features: [
      { name: 'Campanhas', desc: 'CRUD de campanhas via Google Ads API.' },
      { name: 'Ad groups', desc: 'Gerencie grupos de anuncios.' },
      { name: 'Search/Display/YouTube', desc: 'Todos os tipos de campanha.' },
      { name: 'Relatorios', desc: 'Performance e metricas.' },
      { name: 'Conversoes', desc: 'Tracking de conversoes.' },
    ],
  },
  'social-media-mcp-server': {
    slug: 'social-media-mcp-server',
    title: 'Social Media MCP Server',
    headline: 'Social Media MCP Server',
    description: 'Model Context Protocol server para AI agents. Claude, Cursor e qualquer LLM podem criar, agendar e analisar posts.',
    category: 'specialized',
    features: [
      { name: 'MCP protocol', desc: 'Model Context Protocol da Anthropic.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts, get_analytics, upload_media.' },
      { name: 'stdio + HTTP', desc: 'Dois modos de operacao.' },
      { name: 'Claude integration', desc: 'Claude Code e Claude Desktop.' },
      { name: 'Cursor integration', desc: 'Cursor IDE.' },
      { name: 'npm package', desc: 'Instale via npm.' },
    ],
  },
  'social-media-cli': {
    slug: 'social-media-cli',
    title: 'Social Media CLI',
    headline: 'Social Media CLI',
    description: 'Linha de comando para publicar em redes sociais. Publique do terminal sem escrever codigo.',
    category: 'specialized',
    features: [
      { name: 'Publicar do terminal', desc: 'stackpost post --text "Hello" --platforms instagram,facebook' },
      { name: 'Agendar', desc: 'stackpost schedule --time "2026-08-27T10:00:00Z"' },
      { name: 'Listar contas', desc: 'stackpost accounts list' },
      { name: 'Analytics', desc: 'stackpost analytics --post abc123' },
      { name: 'Upload', desc: 'stackpost upload ./video.mp4' },
      { name: 'npm package', desc: 'Instale via npm.' },
    ],
  },
  'claude-code-social-media': {
    slug: 'claude-code-social-media',
    title: 'Claude Code Social Media',
    headline: 'Claude Code + StackPost',
    description: 'Integre StackPost com Claude Code via MCP server. Crie, agende e analise posts direto do Claude.',
    category: 'specialized',
    features: [
      { name: 'MCP server', desc: 'Model Context Protocol integration.' },
      { name: 'Claude Code', desc: 'Use Claude Code para publicar.' },
      { name: 'Claude Desktop', desc: 'Use Claude Desktop para publicar.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts, get_analytics.' },
      { name: 'Setup em 1 comando', desc: 'npx stackpost mcp install claude' },
    ],
  },
  'cursor-social-media': {
    slug: 'cursor-social-media',
    title: 'Cursor Social Media',
    headline: 'Cursor + StackPost',
    description: 'Integre StackPost com Cursor IDE via MCP server. Crie e agende posts direto do editor.',
    category: 'specialized',
    features: [
      { name: 'MCP server', desc: 'Model Context Protocol integration.' },
      { name: 'Cursor IDE', desc: 'Use Cursor para publicar.' },
      { name: 'AI caption', desc: 'Gere captions com AI direto no editor.' },
      { name: 'Tools', desc: 'create_post, schedule_post, list_accounts, get_analytics.' },
      { name: 'Setup em 1 comando', desc: 'npx stackpost mcp install cursor' },
    ],
  },
};

export const auxPages: Record<string, SEOPageData> = {
  'platforms': {
    slug: 'platforms',
    title: 'Todas as Plataformas',
    headline: '15 plataformas suportadas',
    description: 'StackPost suporta Instagram, TikTok, YouTube, Facebook, LinkedIn, X, Threads, Pinterest, Reddit, Bluesky, Mastodon, Discord, Slack, Google Business e Snapchat.',
    category: 'api',
    features: [
      { name: 'Instagram', desc: 'Post, Reel, Story. Carousel ate 10 items. Meta Graph API.' },
      { name: 'TikTok', desc: 'Video e Photo Mode. Content API oficial.' },
      { name: 'YouTube', desc: 'Video e Shorts. Data API v3. Monetizacao.' },
      { name: 'Facebook', desc: 'Page post, Reel, Story. Meta Graph API.' },
      { name: 'LinkedIn', desc: 'Perfil e Company Page. Marketing API.' },
      { name: 'X / Twitter', desc: 'Tweet com midia. API v2.' },
      { name: 'Threads', desc: 'Texto, midia, poll, gif, link.' },
      { name: 'Pinterest', desc: 'Pin com board. API v5.' },
      { name: 'Reddit', desc: 'Text, link, midia, gallery.' },
      { name: 'Bluesky', desc: 'AT Protocol. Descentralizado.' },
      { name: 'Mastodon', desc: 'Instancia custom. Status.' },
      { name: 'Discord', desc: 'Webhook URL. 10 attachments.' },
      { name: 'Slack', desc: 'Webhook URL. 4 attachments.' },
      { name: 'Google Business', desc: 'STANDARD, EVENT, OFFER, ALERT.' },
      { name: 'Snapchat', desc: 'Story e Spotlight. Marketing API.' },
    ],
  },
  'errors': {
    slug: 'errors',
    title: 'API Error Reference',
    headline: 'API Error Reference',
    description: 'Referencia completa de erros da API do StackPost. errorsVerbose com code, userFacingMessage e isTransient.',
    category: 'api',
    features: [
      { name: 'errorsVerbose', desc: 'Todo erro retorna code, userFacingMessage e isTransient.' },
      { name: 'Error codes', desc: 'Codigos padronizados por plataforma e tipo.' },
      { name: 'isTransient', desc: 'Indica se o erro e temporario (retry) ou permanente.' },
      { name: 'Platform errors', desc: 'Meta:190 (token expired), Meta:368 (rate limited), etc.' },
      { name: 'Actionable context', desc: 'Erros faceis a debugar sem adivinhacao.' },
    ],
  },
  'multi-tenant-social-media-api': {
    slug: 'multi-tenant-social-media-api',
    title: 'Multi-Tenant Social Media API',
    headline: 'Multi-Tenant Social Media API',
    description: 'Modele clientes, equipes, marcas e localidades como workspaces separados. Cada tenant tem suas contas, posts e analytics.',
    category: 'api',
    features: [
      { name: 'Organizations', desc: 'Multi-tenancy. Cada org tem sua cota e billing.' },
      { name: 'Teams', desc: 'Times dentro de orgs. Permissoes por team.' },
      { name: 'Workspace separado', desc: 'Contas, posts, uploads, analytics e errors isolados.' },
      { name: 'RBAC', desc: 'Owner, admin, editor, viewer.' },
      { name: 'Audit log', desc: 'Todas as acoes registradas.' },
    ],
  },
  'white-label-social-media-api': {
    slug: 'white-label-social-media-api',
    title: 'White Label Social Media API',
    headline: 'White Label Social Media API',
    description: 'Power your own branded dashboard, client portal, approval flow, or embedded scheduler with StackPost.',
    category: 'api',
    features: [
      { name: 'Sua marca', desc: 'Dashboard com sua marca e identidade visual.' },
      { name: 'Client portal', desc: 'Portal de clientes white-label.' },
      { name: 'Approval flow', desc: 'Fluxo de aprovacao customizavel.' },
      { name: 'Embedded scheduler', desc: 'Agendador embutido no seu produto.' },
      { name: 'API-first', desc: 'Tudo via API. Voce monta a interface.' },
    ],
  },
  'upload-post-alternative': {
    slug: 'upload-post-alternative',
    title: 'Alternativa ao Upload-Post',
    headline: 'StackPost: a alternativa completa ao Upload-Post',
    description: 'Plataforma developer-first com API REST, dashboard e MCP server. O Upload-Post é uma ferramenta visual de agendamento; o StackPost é API + interface + automação programável em um só lugar, com 15 plataformas, legendas com IA e multi-usuário com RBAC sem cobrança por seat.',
    category: 'comparison',
    features: [
      { name: 'API REST completa', desc: '114 endpoints documentados com OpenAPI 3.1 para automação total. O Upload-Post não expõe API pública.' },
      { name: '15 plataformas', desc: 'Cobertura ampla de canais em um único endpoint unificado. O Upload-Post suporta menos plataformas.' },
      { name: 'MCP server + CLI', desc: 'Agents de IA publicam posts via Model Context Protocol direto no terminal. O Upload-Post não oferece.' },
      { name: 'Webhooks com replay', desc: '9 eventos em tempo real com retentativa automática e reprocessamento garantido. O Upload-Post não tem.' },
      { name: 'Multi-usuário com RBAC', desc: 'Controle granular de permissões sem custo por seat. O Upload-Post cobra por usuário.' },
      { name: 'Legendas com IA', desc: 'Geração de variações de copy com Nexus IA integrada. O Upload-Post tem IA básica.' },
      { name: 'Analytics com histórico indefinido', desc: 'Snapshot diário com gráfico de evolução das métricas. O Upload-Post retém dados por tempo limitado.' },
      { name: 'Preço em BRL', desc: 'Pagamento via Mercado Pago, sem IOF nem variação cambial. O Upload-Post cobra em USD.' },
    ],
    faqs: [
      { q: 'O StackPost é uma alternativa ao Upload-Post?', a: 'Sim. O StackPost vai além do agendamento visual: entrega API REST, MCP server, webhooks com replay e multi-usuário com RBAC, ideal para developers e times que precisam de automação e integração programável.' },
      { q: 'Posso migrar do Upload-Post?', a: 'Sim. A API do StackPost segue padrões REST e nossa equipe acompanha a migração das suas contas, conteúdo e agendamentos passo a passo.' },
    ],
  },
};
